### ISSUE TITLE
Allowing arbitrary updates to the progress bar

### ISSUE THREAD

**Issue by ivannp** [prompt-toolkit/python-prompt-toolkit#1016]
Really happy to see the progress bar support!

Allowing updates on the progress bar via _item_updated_ is a good addition, but I would prefer to have an _update_ function which takes an arbitrary value (less than the total).

This is useful in a scenario where files are processed: the total is best set as the total sum of bytes over all files. The value is updated after each file, adding the processed bytes.

What do you think?

**Comment by jonathanslenders** [comment]
Hi @ivannp,

I assume you're talking about ``item_complete()``, not ``item_updated`` as this doesn't exist.

``item_completed`` can be assigned already, like this:

```python
    with ProgressBar() as pb:
        counter = pb(total=10)
        for i in range(800):
            counter.items_completed = i % 10
            time.sleep(1)
```

Does that help? Or do you prefer a different API?

**Comment by ivannp** [comment]
I missed something. :) Works, thanks.
