### ISSUE TITLE
Input is not to a terminal (fd=0) error (within git hook)

### ISSUE THREAD

**Issue by menaveenshankar** [prompt-toolkit/python-prompt-toolkit#1030]
Hello,
  I am trying to use prompt_toolkit within a git hook (prepare-commit-msg). I get this  warning - **Input is not to a terminal (fd=0)** I would appreciate any pointers on how to solve this.

I am using python 3.7.5. ```prompt_toolkit.__version__ = '2.0.10' ```

screenshot of the errors that follow -
<img width="1220" alt="prompt_toolkit_fail_githook" src="https://user-images.githubusercontent.com/15365471/70848413-146ffd00-1e97-11ea-9f9d-68ab101c22ad.png">

**Comment by halloleo** [comment]
Not an expert on `prompt-toolkit`, but I would guess the problem is that prompt-toolkit
 expects to be connected to a tty and in your hook you might not have a tty. I assume prompt-toolkit is called by a parent app. Why is that app calling into prompt-toolkit?

**Comment by menaveenshankar** [comment]
Hi halloleo, I have a tty connected, i.e. ```sys.stdin = open('/dev/tty', 'r')```  before I call the ```prompt()``` function. I am implementing autocomplete feature in the hook (the hook itself is in python). If I call the same functionality as a normal python script it works fine, but not within the hook environment even though I have a tty.

**Comment by halloleo** [comment]
`prompt-toolkit` needs unfortunately more than just a minimal tty. (see #1032).

**Comment by menaveenshankar** [comment]
> `prompt-toolkit` needs unfortunately more than just a minimal tty. (see #1032).

ah i see, thanks for the info. On a related note, I tried a simpler version of autocomplete with the ```readline``` package, still doesn't work (posted it in sof too - [link](https://stackoverflow.com/questions/59357934/autocomplete-does-not-work-within-git-hook-tty-problem) ). seems like there is some other issue within the git hook environment.
