### ISSUE TITLE
to exit external editor without saving is considered successful edit

### ISSUE THREAD

**Issue by pasenor** [prompt-toolkit/python-prompt-toolkit#1031]
After I invoke external editor with the default `edit-and-execute-command` handler, there is no way to cancel the edit: it is always considered successful, and the resulting query is always invoked. It would be more intuitive to only consider an editing session successful when the user explicitly saves changes on exit, and to simply return control if they are discarded.

It would also save some cycles, since the document doesn't need to always be re-read.

**Comment by jonathanslenders** [comment]
I don't think that's right. Prompt_toolkit should considers the exit status of the $EDITOR, similar to what GNU Readline does. In Vi, this means, :cq will cancel.

**Comment by pasenor** [comment]
> :cq will cancel.

Wow, didn't know you can force vim to exit with an error code with :cq. it works indeed!

However, I would expect :q! to do the same thing, even even though the editor exits normally, and to "execute" the query only if something has been written to the temp file. Point in case: if the editor is nano, it seems the only way to exit with an error code is to kill it externally. [Here](https://github.com/dbcli/mycli/issues/762#issuecomment-565478765) is a similar complaint to mycli: the user expects :q! to cancel editing.

**Comment by jonathanslenders** [comment]
Well, the way it works right now, is exactly like GNU Readline works, which is used by many thousands of applications. If Nano cannot handle it, then maybe this should become a feature request for Nano?

It is possible to change the behavior with a custom key binding. `Buffer.open_in_editor` takes a `validate_and_handle=True` argument, which when set to `False`, won't accept the input right away.

Another option is probably to create a little shell script that wraps around Nano.

**Comment by pasenor** [comment]
Yes, the mycli case is easily handled by overwriting `Buffer.open_in_editor`, I just felt that the default behavior is counter-intuitive. But if it's an established convention, then there is not much to talk about. Thank you for the explanation.
