### ISSUE TITLE
[PT 3.0.2] TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by Brittank88** [prompt-toolkit/python-prompt-toolkit#1048]
Any use (yes, even if there's no formatting whatsoever) of the `print_formatted_text()` function causes [the following error](https://hatebin.com/hcqbjdazrt).

Weirdly enough, it actually does still print the text with the right colouring (only when using ANSI colours though, HTML colours don't work...):
![image](https://user-images.githubusercontent.com/24266948/71947457-0d7fa480-3221-11ea-9f37-b754934aab65.png)

I wonder if this is to do with running my code from within Visual Studio Code, as no error occurs when using a Python terminal or a standard terminal to run a python file with this code. I have no idea why this would be though.

Let me know if you need any more information or want me to do any testing!

P.S. I have tried this same code with PT 2.0.10 and **it works perfectly fine with no issues**. Likely something in the 3.x versions of PT has broken this functionality somehow.

**Comment by jonathanslenders** [comment]
It looks like Visual Studio Code replaces ``sys.stdout`` with another object, which doesn't support writing bytes. 

Can you try this:
```python
import sys
sys.stdout.buffer.write(b'somebytes')
```

If that doesn't work, it's a bug in Visual Studio Code.

**Comment by Brittank88** [comment]
You are correct, this code causes the same error:
`TypeError: Object of type bytes is not JSON serializable`

Forgive me for asking, but what would be the best course of action from here? Raise an issue with the VSCode devs?

**Comment by Brittank88** [comment]
Closing as this error does not occur on VSCode Insider, indicating a fix will follow for the standard VSCode releases.

(Thanks for your help Jonathan!)
