### ISSUE TITLE
completer stop working when the '=' character is typed

### ISSUE THREAD

**Issue by jorgeallyson** [prompt-toolkit/python-prompt-toolkit#1060]
I am trying something like this:
choices=('ou=something,ou=somethingelse', 'ou=something1,ou=somethingelse1')
ou_completer=FuzzyWordCompleter(choices)
selected_ou=prompt('Choose OU: ', completer=ou_completer, validator=OUValidator(), validate_while_typing=False)
Everything is working until I type the '=', then the completer simply stop showing the options. This is unexpected unless the '=' has some undocumented special meaning in this situation.

**Comment by jonathanslenders** [comment]
@jorgeallyson ,

Can you try passing ``WORD=True`` to ``FuzzyWordCompleter``? This uses whitespace as a separator instead of any non-alphanumeric character.

An alternative is to pass a custom regex pattern.

**Comment by jorgeallyson** [comment]
@jonathanslenders 
WORD=True will do for the moment. I will try to learn how to pass a custom regex.
Thank you.
