### ISSUE TITLE
Prompt using multiprocessing causes KeyError

### ISSUE THREAD

**Issue by bt235711** [prompt-toolkit/python-prompt-toolkit#1077]
prompt-toolkit 3.0.3 
Ubuntu 18.04.4
Python 3.7.5

```
import multiprocessing
from prompt_toolkit import prompt

def run_console():
    print('You said: %s' % prompt('>>>: '))

process = multiprocessing.Process(target=run_console)
process.start()
```
$ python ptk_test.py

Warning: Input is not a terminal (fd=3).Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 251, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '3 is not registered'

**Comment by laixintao** [comment]
I don't think it is necessary to support multiprocess for prompt-toolkit, it needs to read user's input, so it should only work as an front-end process.

Why do you need multiprocessing in the first place?

**Comment by bt235711** [comment]
I am using this to simplify reloading in my application. Based on the exit code, the thread is spawned again if reload is intended.
I am only seeing this in linux, the windows build works fine.

**Comment by jonathanslenders** [comment]
I would not recommended this. IMHO sub processes shouldn't do user interaction, but if we can make it work, that would be nice.

The reason it works on Windows is probably because input/output doesn't go through file descriptors, but through the console input/output handles.

Weird is that the input is taken from fd3 in this case. Normally it's fd0. I'm not sure where this is coming from.

**Comment by bt235711** [comment]
I was able to make it work by creating input and output with the always_prefer_tty flag set for the PromptSession.

```
import multiprocessing
import sys

from prompt_toolkit import PromptSession, input, output
from prompt_toolkit.patch_stdout import patch_stdout


def run_console():
    with patch_stdout():        
        i = input.create_input(always_prefer_tty=True)
        o = output.create_output(always_prefer_tty=True)
        session = PromptSession(input=i, output=o)        
        sys.exit(int(session.prompt('>>>: ')))

exit_code = 3
while exit_code == 3:
    process = multiprocessing.Process(target=run_console)
    process.start()
    process.join()
    exit_code = process.exitcode
```
