### ISSUE TITLE
RuntimeError: This event loop is already running" if application is run from inside a running event loop

### ISSUE THREAD

**Issue by brianmaissy** [prompt-toolkit/python-prompt-toolkit#1084]
After recently upgrading ipython from 7.9.0 to 7.12.0, which involved upgrading prompt_toolkit from 2.0.10 to 3.0.3, I have a problem.

I use ipdb to debug tests, and until now (with prompt_toolkit 2.0), calling `ipdb.set_trace()` from within a running event loop worked fine. Now, it (very understandably) results in the following exception:

```
../../.local/lib/python3.6/site-packages/IPython/terminal/debugger.py:114: in cmdloop
    line = self.pt_app.prompt()
../../.local/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py:997: in prompt
    return self.app.run()
../../.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py:810: in run
    return loop.run_until_complete(self.run_async(pre_run=pre_run))
/usr/lib/python3.6/asyncio/base_events.py:471: in run_until_complete
    self.run_forever()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def run_forever(self):
        """Run until stop() is called."""
        self._check_closed()
        if self.is_running():
>           raise RuntimeError('This event loop is already running')
E           RuntimeError: This event loop is already running

/usr/lib/python3.6/asyncio/base_events.py:425: RuntimeError
```

Now the question is what to do about this, and whether or not my use case (which I'm guessing is relatively common) can continue to be supported.

I debated whether this is a prompt_toolkit issue or an ipython (or even ipdb) one, but it's probably both. If prompt_toolkit has an equivalent entry point that can be called from a running event loop, then it's just a matter of asking ipython to use it. But if not, I wonder if such an entry point could be created. If not, suggestions for workarounds that ipython/ipdb could use to solve this on their end are welcome.

**Comment by jonathanslenders** [comment]
I think this can be fixed. IPython should create a new event loop for ipdb and swap that for the current loop right before calling the pdb prompt.

I think we were doing this in IPython actually, so something could be wrong with that code.

**Comment by brianmaissy** [comment]
Fixed in ipython: https://github.com/ipython/ipython/pull/12141

**Comment by MrMino** [comment]
@brianmaissy based on [my comment in ipdb/184](https://github.com/gotcha/ipdb/issues/184#issuecomment-762612875), would you please consider reopenning this issue?
