### ISSUE TITLE
Broken on Python 3.6.0: missing typing.AsyncGenerator

### ISSUE THREAD

**Issue by cooijmanstim** [prompt-toolkit/python-prompt-toolkit#1085]
This package is currently broken on Python 3.6.0 as it requires `typing.AsyncGenerator` which wasn't introduced until 3.6.1.

Traceback fragment:

```python
  File ".../prompt_toolkit/application/current.py", line 8, in <module>
    from prompt_toolkit.eventloop.dummy_contextvars import ContextVar  # type: ignore
  File ".../prompt_toolkit/eventloop/__init__.py", line 1, in <module>
    from .async_generator import generator_to_async_generator
  File ".../prompt_toolkit/eventloop/async_generator.py", line 5, in <module>
    from typing import AsyncGenerator, Callable, Iterable, TypeVar, Union
ImportError: cannot import name 'AsyncGenerator'
```

I'm not attached to Python 3.6.0 but it took me a while to figure out why conda kept giving me a broken environment. Maybe refine the dependency to >=3.6.1?

**Comment by jonathanslenders** [comment]
I guess it too late now, I can't remove all the published builds from PyPI, but I'll fix it in setup.py.

**Comment by jonathanslenders** [comment]
See: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1090
