### ISSUE TITLE
Update readme to mention support for newer versions of Python

### ISSUE THREAD

**Issue by Nicholas-Steel** [prompt-toolkit/python-prompt-toolkit#1097]
https://github.com/prompt-toolkit/python-prompt-toolkit/edit/master/docs/index.rst

Line 39, change it to say 3.6+ as the highest supported release, this'll bring it in line with the start of the document.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/73f98ee9306a240c0202cf3e69b914787f90f8ea
Thanks for mentioning!
