### ISSUE TITLE
Async fullscreen application dialog unresponsive

### ISSUE THREAD

**Issue by linkous8** [prompt-toolkit/python-prompt-toolkit#1100]
(Full (but brief) code to replicate the issue is attached)

Using toolkit version 3.0.4 under python 3.6.10

I'm writing an application that uses a full-screen prompt application as the view (imb_tui.py) to keep the business logic (imb.py) separate from the presentation. To prevent flickering, I launch the app with run_async and swap out the body of the main application frame to switch screens.

The run_async task starts the app with a frame around an empty window, then the business logic task calls a method to swap the body of the frame with an HSplit containing my prompt then awaits for one of the yes/no handlers to execute before returning the result. The problem is the updated frame body does not get drawn to the screen until there is keyboard input (eg. the 'n' key). However, even though the dialog is drawn, it is not responsive to any keystrokes except for Enter which triggers the yes handler. Further, if you press Enter as the first keystroke (before the dialog is drawn) it will trigger the yes handler.

Could you take a look at my example code and let me know if I have set up the application incorrectly? To run: `python3.6 imb.py`

[imb.py.txt](https://github.com/prompt-toolkit/python-prompt-toolkit/files/4340639/imb.py.txt)
[imb_tui.py.txt](https://github.com/prompt-toolkit/python-prompt-toolkit/files/4340640/imb_tui.py.txt)

**Comment by jonathanslenders** [comment]
Hi @linkous8,

Can you try adding ``self.app.invalidate()`` after assigning to ``self.app_frame.body`? The assignment alone won't trigger a paint.

Let me know if it still doesn't work. I took your code, and it actuall seems to run fine with this little change.

**Comment by linkous8** [comment]
That worked, thank you @jonathanslenders
