### ISSUE TITLE
PromptSession does not execute commands when pasting copied multi-line text.

### ISSUE THREAD

**Issue by alexxbar** [prompt-toolkit/python-prompt-toolkit#1102]
```
    while True:
        session = PromptSession()
        line = session.prompt(
            message=">>> ",
            multiline=False,
        )

        print("::: " + line)
```

_For example, we want to paste the copied text:_
```
help
exit
```

**Expected Result:**
Commands are executed sequentially, one after another

**Actual result:**
    Copy-paste input occurs and is displayed on the screen as a few lines
    The console starts processing the command only after pressing Enter
    The console interprets the entered copy-paste as one command line, which it cannot process, and returns an error

Example with **raw_input**:
```
    while True:
        line = raw_input(">>> ")
        print("::: " + line)
```

**Comment by jonathanslenders** [comment]
Hi @alexxbar,

This is actually a security feature, called bracketed paste: https://cirw.in/blog/bracketed-paste

If you want the individual lines, it's recommended to do ``line.splitlines()`` or something like that.
If you really don't want to do that, then it's probably possible to create a custom ``Output`` class that doesn't enable bracketed paste, and pass that into ``PromptSession``.

**Comment by alexxbar** [comment]
Thanks!
I did it something like this:
```
from prompt_toolkit.output.vt100 import Vt100_Output

class Vt200_Output(Vt100_Output):
    def enable_bracketed_paste(self):
        pass
    def disable_bracketed_paste(self):
        pass

output = Vt200_Output.from_pty(sys.__stdout__, term=os.environ.get('TERM', ''))
session = PromptSession(output=output)
```
