### ISSUE TITLE
print_formatted_text function raises UnsupportedOperation when executed in pytest

### ISSUE THREAD

**Issue by StanSvec** [prompt-toolkit/python-prompt-toolkit#1107]
I use **prompt_toolkit.print_formatted_text** function for printing colored text and it works nicely when it is executed as a python app. However when the same code is unit tested using pytest then **io.UnsupportedOperation** error is raised.

cls = <class 'prompt_toolkit.output.vt100.Vt100_Output'>
stdout = <_io.TextIOWrapper encoding='UTF-8'>, term = ''

    @classmethod
    def from_pty(cls, stdout: TextIO, term: Optional[str] = None) -> "Vt100_Output":
        """
        Create an Output class from a pseudo terminal.
        (This will take the dimensions by reading the pseudo
        terminal attributes.)
        """
        # Normally, this requires a real TTY device, but people instantiate
        # this class often during unit tests as well. For convenience, we print
        # an error message, use standard dimensions, and go on.
>       fd = stdout.fileno()
E       io.UnsupportedOperation: fileno

../venv/lib/python3.8/site-packages/prompt_toolkit/output/vt100.py:449: UnsupportedOperation

Is there anything I can do to prevent this error? I just need to test that certain output is printed to the console. The formatting doesn't need work in unit tests.

**Comment by jonathanslenders** [comment]
I assume you're testing some code that happens to contain calls to ``print_formatted_text``. You don't want to test the ``print_formatted_text`` function itself. Right?

Probably, the easiest is to monkey patch ``prompt_toolkit.output.defaults.create_output`` and make it always return a ``prompt_toolkit.output.base.DummyOutput`` instance.

I don't like monkey patching though. The right way would probably to take the current  ``prompt_toolkit.application.current.AppSession``, using ``prompt_toolkit.application.current.get_app_session()`` and change the output from the ``AppSession`` to a ``DummyOutput``. Can you try this? I'd like to know whether that works.

**Comment by jonathanslenders** [comment]
Something like this should work:
```python
from prompt_toolkit.application import create_app_session
from prompt_toolkit.shortcuts import print_formatted_text
from prompt_toolkit.output import DummyOutput

with create_app_session(output=DummyOutput()):
    print_formatted_text('hello')
```

**Comment by StanSvec** [comment]
Hi Jonathan,

Thanks for taking the time to come with the solution. I wasn't very specific in the OP. I use this toolkit indirectly by utilizing pypager library. However paging is optional so when it's disabled I'm calling `print_formatted_text` directly. I need to test that the output is printed correctly, but the formatting is not tested.
By your explanation I came to the solution to inherit from DummyOutput, override `write` method to print to stdout and set it as an output in unit tests. And it seems to work fine. If you know about any even simpler solution please let me know. Otherwise feel free to close the ticket.

Thanks again!

**Comment by jonathanslenders** [comment]
Inheriting ``DummyOutput`` sounds like the right thing to do.

FYI: Some days ago, I added this documentation: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1113/files
