### ISSUE TITLE
[Question] Possible to close completion popup programatically?

### ISSUE THREAD

**Issue by blmorant** [prompt-toolkit/python-prompt-toolkit#1149]
Is it possible to close or hide the completion popup programatically? I have dug through the docs but can't seem to find a way to do it. I want to hook up the Esc key to close the completion window.

Thanks!

**Comment by MrMino** [comment]
If you're using `CompletionsMenu`, you can pass [`prompt_toolkit.filters.Condition`](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#prompt_toolkit.filters.Condition) to the `extra_filter` parameter, and control the visibility using that.
