### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by lorencarvalho** [prompt-toolkit/python-prompt-toolkit#1174]
Hello!

I'm writing to kindly ask that y'all cut a new release to PyPI, if you can. I'm not sure what (if any) prompt_toolkit's release cadence is, but I am currently feeling the pain of missing the `py.typed` marker file in 3.0.5:

`error: No library stub file for module 'prompt_toolkit'`

This is the commit that included it, https://github.com/prompt-toolkit/python-prompt-toolkit/commit/f0b4cda0bfde17b479ce23b7aa29455dc003d683

Thanks in advance!

**Comment by jonathanslenders** [comment]
Hi @lorencarvalho,

This took a bit longer than expected, sorry for the wait. A new release was pushed earlier this week. It should include that commit.
