### ISSUE TITLE
Autocompleting words with special characters?

### ISSUE THREAD

**Issue by Nahnahchi** [prompt-toolkit/python-prompt-toolkit#1201]
I've been struggling with a pretty frustrating issue.
I'm using a Nested Completer with words that often include dashes. I've noticed that if you are trying to complete something like `verb-example`, then it would work fine if I just type `verb` and press *tab*, but if it's `verb-`, the completer will get confused and ignore the previous input. This results in unreliable autocompletion in my application.

Is there a fix or at least a workaround to this problem?

**Comment by jonathanslenders** [comment]
This sounds like a bug. Thanks for reporting!

I wonder if it'll be fixed if we pass ``WORD=True`` (or a custom pattern) to ``WordCompleter`` on this line: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/completion/nested.py#L105

**Comment by Nahnahchi** [comment]
Thanks fo the reply!

I've overriden this method and included `WORD=True`, this has resolved the issue. Will use this small derived class for now.
