### ISSUE TITLE
PromptToolkitSSHSession._interact may fail on self._chan.set_line_mode(False)

### ISSUE THREAD

**Issue by JoshHeitzman** [prompt-toolkit/python-prompt-toolkit#1207]
I observed this call fail in two different ways:
1.  When self._chan is of the type asyncssh.editor.SSHLineEditorChannel and its self._editor is None the set_line_mode function raises an exception as tries to make a call on self._editor.
2.  When asyncssh.listen is called with the kwarg line_editor=False.  In this case the type of self._chan is asyncssh.channel.SSHServerChannel and lacks a set_line_mode method.

In both cases I was able to workaround by putting the set_line_mode call under the condition:

if hasattr(self._chan, 'set_line_mode') and self._chan._editor is not None:

and the ssh example then worked fine, so it appears that the need to call set_line_mode is limited to specific configuration and isn't possible in other configuraitons.

**Comment by jonathanslenders** [comment]
Closing this now that #1210 has been merged. Feel free to open again.
