### ISSUE TITLE
The little Stdout class in PromptToolkitSSHSession is missing an encoding property

### ISSUE THREAD

**Issue by JoshHeitzman** [prompt-toolkit/python-prompt-toolkit#1209]
prompt_toolkit.output.vt100.Vt100_Output.encoding method expects a the instance it is holding in its self.stdout attribute to have an encoding attribute/property.  However, the prompt_toolkit.contrib.ssh.PromptToolkitSSHSession.__init__ method has a little Stdout class that lacks such an attribute/property and Vt100_Output will have an instance of that little Stdout class in the ssh server case.

I worked around this by adding this property to that little Stdout class:
            @property
            def encoding(s):
                return self._chan._orig_chan.get_encoding()[0]

**Comment by JoshHeitzman** [comment]
Oh, this came in the context of the text editor example having been modified to be served up over SSH and then the ShowLeadingWhiteSpaceProcessor was added as an input processor for the TextArea.

**Comment by jonathanslenders** [comment]
@JoshHeitzman, thank you for pointing out this issue. Can you create a pull request for this?

**Comment by JoshHeitzman** [comment]
@jonathanslenders the PR https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1210 the changes with the code mentioned above and the code mentioned in https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1207 since they are in the same file and both were necessary for the ssh serving scenario I'm working on.

**Comment by jonathanslenders** [comment]
Closing this now that #1210 has been merged. Feel free to open again.
