### ISSUE TITLE
Placeholder text

### ISSUE THREAD

**Issue by Yajo** [prompt-toolkit/python-prompt-toolkit#1214]
I'd like to have a prompt that, instead of having a default value, has a placeholder text, so when the prompt is completely empty, it displays that text grayed out.

**Comment by jonathanslenders** [comment]
Hi @Yajo, excellent suggestion.
I think something like this should do it: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1215/files

**Comment by Yajo** [comment]
Yes! Awesome! Thanks!
