### ISSUE TITLE
get_word_before_cursor returning an empty string

### ISSUE THREAD

**Issue by rulioj** [prompt-toolkit/python-prompt-toolkit#1218]
hi

So, I was making a custom completer and I came across a problem: in all situations (where the 'pattern' argument is None), the "get_word_before_cursor" method did not return the last written word.

```
from prompt_toolkit.completion import Completer, Completion, FuzzyCompleter
from prompt_toolkit.output.color_depth import ColorDepth
from prompt_toolkit.shortcuts import CompleteStyle, prompt
from prompt_toolkit.document import Document

commands = {
    'ls': { 'home': None, 'dist': None, 'docker': None},
    'code': {
        '-inject': {'dll': None, 'gzip': None},
        '-supply': {'ssh': None, 'ftp': None, 'http': {'apache': None, 'nginx': None}}
    },
}

class ColorCompleter(Completer):
    def get_completions(self, document: Document, complete_event):
        word = document.get_word_before_cursor(WORD=True)
        
        if not word:
            for cmd in commands:
                yield Completion(
                    cmd
                )
            return None
        
        print(f'\nWord returned! {word}', flush=True)

def main():
    
    while True:
        prompt(
            "> ",
            completer=FuzzyCompleter(ColorCompleter()),
            complete_style=CompleteStyle.READLINE_LIKE,
        )


if __name__ == "__main__":
    main()

```

in #823, was said:
"if WORD=True is given, this will take any whitespace as a separator."

but, in [document.py](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/document.py#L455), function '_is_word_before_cursor_complete' does not check the WORD parameter.

then, if no pattern is passed, this piece of code will be reached
```
return (
   self.text_before_cursor == "" or self.text_before_cursor[-1:].isspace()
)
```

text_before_cursor will not be "", but self.text_before_cursor[-1:].isspace() will be true, and since there is no check for the WORD parameter, this will cause ...

```
if self._is_word_before_cursor_complete(WORD=WORD, pattern=pattern):
    # Space before the cursor or no text before cursor.
    return ""
```
... to return "".

in my example code, the output would look something like this:
```
> [TAB]
ls   code 
> code[TAB]    <- this does nothing, since the is no space beween the cursor and the word "code"
> code [TAB]   <- now there is a space, causing 'get_word_before_cursor' to return "", even if WORD=True
ls   code
```

a small solution that I implemented, was to check if the WORD parameter is false:

before:
```
    def _is_word_before_cursor_complete(
        self, WORD: bool = False, pattern: Optional[Pattern[str]] = None
    ) -> bool:
        if pattern:
            return self.find_start_of_previous_word(pattern=pattern) is None
        else:
            return (
                self.text_before_cursor == "" or self.text_before_cursor[-1:].isspace()
            )
```

after:
```
def _is_word_before_cursor_complete(
        self, WORD: bool = False, pattern: Optional[Pattern[str]] = None
    ) -> bool:
        if pattern:
            return self.find_start_of_previous_word(pattern=pattern) is None
        else:
            return (
                (self.text_before_cursor == "" or self.text_before_cursor[-1:].isspace()) and not WORD
            )
```

now the output look like this:
```
> [TAB]
ls   code 
> code[TAB]          <-- does nothing as expected...
> code [TAB]
Word returned! code         <-- now the last word returned!
```

I also noticed that when there is no space between the cursor and the last word, 'self.text_before_cursor' will be an empty string. I don't know if this is the normal behavior of the library...

Anyway, this is the first time i open an issue on github, i hope i did it in a way that it is possible to understand the problem. tks!

**Comment by jonathanslenders** [comment]
I think the solution is to generate the space as part of the completion:

So, instead of:
```python
yield Completion(cmd)
```
do:
```python
yield Completion(cmd + ' ', display=cmd)
```

Also see: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1245 
-> Not an answer to the question, but I think the WORD parameter should be passed along in that function.
