### ISSUE TITLE
Missing whitespace

### ISSUE THREAD

**Issue by seanfarley** [prompt-toolkit/python-prompt-toolkit#1233]
This is a weird issue and hard to pin down since there are so many moving parts. I've tested multiple versions of my shell (`xonsh`) and multiple versions of prompt_toolkit and by rolling back to ptk2 I was able to revert this observed behavior. `xonsh` has a lot of config knobs and they refactored for ptk3 so it's not entirely off the hook. But I'm not sure where to even diagnose this, so I'll start here.

I'll try my best to describe the issue I'm seeing:

This screenshot shows the cursor is in the wrong place when launching xonsh. The cursor is actually on a space but has not moved on to the right.

<img width="201" alt="Screen Shot 2020-09-06 at 2 39 35 PM" src="https://user-images.githubusercontent.com/20887/92337065-b950ec80-f05b-11ea-8077-0db3022c244b.png">

When typing a non-whitespace character, the cursor updates to the correct position:
<img width="208" alt="Screen Shot 2020-09-06 at 2 39 41 PM" src="https://user-images.githubusercontent.com/20887/92337118-3c724280-f05c-11ea-8154-f617e8e9fc13.png">

After the 'asdf' string, I type many spaces but nothing is updated (so it looks exactly the same as the above screenshot). When I again type a non-whitespace, the cursor updates to the correct location:
<img width="198" alt="Screen Shot 2020-09-06 at 4 17 17 PM" src="https://user-images.githubusercontent.com/20887/92337144-74798580-f05c-11ea-91ff-372d330c8338.png">

Any insight into this would be greatly appreciated; thanks!

**Comment by jonathanslenders** [comment]
Hi @seanfarley,

Does this happen in all terminals? Which terminal are you using?

I expect this could be related to recent changes that remove trailing whitespaces (that was done to make sure these are not included when output is selected and copied from the terminal).

**Comment by seanfarley** [comment]
Sorry for the late reply!

Interesting. For iterm, the behavior seems to be fixed. The screenshots I posted are from my main terminal which is libvterm via emacs.

**Comment by seanfarley** [comment]
Gentle ping :-) This bug is keeping me at ptk 2 which is becoming increasingly challenging.

**Comment by seanfarley** [comment]
I can no longer produce this so it seems either something in prompt-toolkit, libvterm, or both changed to fix it. Yay!
