### ISSUE TITLE
support updating prompt token in background

### ISSUE THREAD

**Issue by jnoortheen** [prompt-toolkit/python-prompt-toolkit#1236]
is it possible to support updating the prompt from a thread? it will help the xonsh prompt to be faster and with multiple tokens (especially git status from large repos). Fish shell has https://github.com/acomagu/fish-async-prompt and this facilitates long running functions to be offloaded.

**Comment by jnoortheen** [comment]
related issue from xonsh repo - https://github.com/xonsh/xonsh/issues/2803

**Comment by jonathanslenders** [comment]
Yes, this is possible.

See, for instance, this example: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/clock-input.py

Passing a ``refresh_interval`` will make prompt_toolkit repaint the prompt every so often.

It is also possible to invalidate the prompt, by calling ``PromptSession.app.invalidate()``. This is thread safe and can be called from another thread. That way, ``refresh_interval`` is not needed. (That's possibly more efficient.)

**Comment by jnoortheen** [comment]
thanks @jonathanslenders . It is very simple than I expected. 

```py
import datetime
import time

from prompt_toolkit import PromptSession
import threading

def get_prompt():
    " Tokens to be shown before the prompt. "
    now = datetime.datetime.now()
    return [
        ("bg:#008800 #ffffff", "%s:%s:%s" % (now.hour, now.minute, now.second)),
        ("bg:cornsilk fg:maroon", " Enter something: "),
    ]

def update_in_bg(session: PromptSession):
    time.sleep(3)
    session.app.invalidate()


def main():
    session = PromptSession()
    t = threading.Thread(target=update_in_bg, args=(session, ))
    t.start()
    result = session.prompt(get_prompt)
    print("You said: %s" % result)



if __name__ == "__main__":
    main()
```

**Comment by jnoortheen** [comment]
Ok I found setting `session.message` directly and then calling `invalidate` solves the issue. Is that correct way to do?
