### ISSUE TITLE
`rprompt` at top of multiline prompt not working since 3.0.6

### ISSUE THREAD

**Issue by sevens** [prompt-toolkit/python-prompt-toolkit#1241]
Hi, I've been using Xonsh with a prompt-toolkit prompt for quite some time.  I have a multi-line prompt with an `rprompt` showing an exit-status indicator 'above' the multi-line prompt (technically it's in the prompt but the first line of the prompt is an empty line, both for visual separation and for the `rprompt` indicator).  Since prompt-toolkit 3.0.6 however, this is no longer working as before: the `rprompt` is now shown at the bottom and my attempts at fixing this haven't succeeded.

A simplified example of my current setup (in Xonsh) which works as expected in 3.0.5 and before:
```
$PROMPT = '\n' + '-' * int($(tput cols)) + '\n\n>>> '
$RIGHT_PROMPT = 'exit_status_indicator'
```

This shows the exit status indicator of the previous command above the visible part of the prompt:
```
                                                      exit_status_indicator
---------------------------------------------------------------------------
                                                                           
>>> 
```

It worked fine in 3.0.5 and earlier (including ptk 2.x).  In 3.0.6 this isn't working anymore, probably due to https://github.com/prompt-toolkit/python-prompt-toolkit/commit/07e3429e50d49349c8bdb02e938825c9e1aa8c26

I've tried 'inverting' my rprompt by suffixing it with newlines to shift it back up to above the dashed separator line but that doesn't seem to work (as it crosses a line that has content at the right-side of the screen as well?).  I.e. suffixing it with 3 newlines:
```
$RIGHT_PROMPT = 'exit_status_indicator\n\n\n'
```

Tested this (both my original prompt and work-around) in ptk 3.0.6 and 3.0.7, not working in either.

Version info:
* Python 3.8.3
* Xonsh: tested with 0.9.13, 0.9.18
* Prompt toolkit: tested with 2.0.10, 3.0.5, 3.0.6, 3.0.7

**Comment by rouhannb** [comment]
For me at least, it isn’t just for multiline prompts. _All_ right prompts (or, at the very least, the simple few I’ve tried) display at the bottom of the screen.
07e3429 is definitely the culprit. Changing it back manually fixes the issue.

**Comment by aspieln3r** [comment]
it's been a year

**Comment by arkhan** [comment]
Any update?

**Comment by ryanobjc** [comment]
Any thought of when #[e5a86e2](https://github.com/jnoortheen/python-prompt-toolkit/commit/e5a86e270e7ee698c849d39196d5a6a0d6e5a331) will hit a pip release?
