### ISSUE TITLE
is there a way to get the effective dimensions a container will be rendered at?

### ISSUE THREAD

**Issue by ale-dd** [prompt-toolkit/python-prompt-toolkit#1242]
I kind of doubt this is possible, but is there a way to get the effective dimensions a container will be rendered at?

I am charting some metrics and given the most recent information will be to the right, it is important that I know how wide my window is. Or else, it would appear as if my metrics were lagging. As a desperate hack, I could just flip the horizontal axis but that would be extremely counter-intuitive.

![Screen Shot 2020-09-12 at 00 02 09](https://user-images.githubusercontent.com/43554026/92989833-1d284a80-f48c-11ea-90fb-5cab4d82831c.png)

Thank you!

**Comment by jonathanslenders** [comment]
Hi @ale-dd,

I assume you are using ``prompt_toolkit.layout.controls.FormattedTextControl``. Is that correct?

With this it is not possible indeed, but you can create your own ``prompt_toolkit.layout.controls.UIControl`` implementation. This has a method ``create_content`` that is supposed for building the ``UIContent`` using a given width and height for rendering.
``UIContent`` needs to receive a callable that returns the line content for a given line number.

**Comment by ale-dd** [comment]
What I am showing in the above screenshot was indeed made by creating a subclass of UIControl. Now that I look back at my code, I feel like an idiot... :)

thank you!
