### ISSUE TITLE
Bind Control+Backspace

### ISSUE THREAD

**Issue by anki-code** [prompt-toolkit/python-prompt-toolkit#1250]
Hello!

Is there a way to bind <kbd>Control</kbd> + <kbd>Backspace</kbd>? This combination used in many editors to remove whole word (i.e. Kate editor).

Thanks!

**Comment by anki-code** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/257#issuecomment-190328366

**Comment by eugenesvk** [comment]
@anki-code By the way, I've submitted two PRs (one for Windows, another for all other systems) (check the comment linked above for more details) that allows exactly this binding as I was finding xonsh without this backward-kill-word shortcut rather unpleasant

`@jonathanslenders` is a bit hesitant re. this applying this change outside of Windows, but hopefully he'd reconsider, maybe you could weigh in as a xonsh shell developer working with Linux — how big of a deal would that change be?
