### ISSUE TITLE
Feature Request: Update full screen application content periodically (without any keybindings)

### ISSUE THREAD

**Issue by kshamsuttoha** [prompt-toolkit/python-prompt-toolkit#1269]
I am building a terminal which polls the status of a system and displays it in a full screen application using prompt_toolkit. While I can update the status using using a keybinding, I would like to be able to be able to poll this information, as opposed to have it user requested. 

I am using 2.0.10 version of prompt toolkit. There appears to be a way to do this, as done in https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/clock-input.py .  But I would like to be able to do this for windows in full screen application. 

Tried a few different work around, could not get it to work. Tried to run the update_table_task on invalidate, and have a thread invalidating the application periodically. But no luck there. 

```
        def update_table_task(self):
            self.table_display.content = FormattedTextControl(self.mk_counter_channel_table())

        # Need a thread to update table info in the background
        def invalidate_task():
            app.invalidate()
            time.sleep(1)

         app = Application(layout=layout, key_bindings=kb, full_screen=True, on_invalidate=self.update_table_task())

        # Start threads.
        t1 = threading.Thread(target=invalidate_task)
        t1.daemon = True
        t1.start()

        app.run()
```

Any existing workaround would be great! If not, a feature like this can be very helpful for applications which poll and talk to other systems.

**Comment by kshamsuttoha** [comment]
The workaround turned out to be fairly simple. A thread running in the background updating the content and invalidating the application works well.

**Comment by JonesKenzie** [comment]
Do you mind to share the solution? @kshamsuttoha 

I'm trying to have a Frame periodically check a sqlite database for updates, but as I'm quite dumb, I can't figure out without some more explanation.

Thanks!
