### ISSUE TITLE
List of key bindings 

### ISSUE THREAD

**Issue by halloleo** [prompt-toolkit/python-prompt-toolkit#1282]
`prompt-toolkit` is fantastic! Thanks a lot!

I was going through the documentation looking for a list of key bindings, say, in Emacs mode, but couldn't find one. Is there anywhere else such a list for the prompt-toolkit?

**Comment by BioBox** [comment]
I couldn't find anything in the documentation either, so when in doubt read the [relevent source](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/6bdcb9d7e33ab25b665ea9b5ba373471737b1db2/src/prompt_toolkit/key_binding/bindings/emacs.py).

**Comment by halloleo** [comment]
@BioBox Thanks. Makes sense.
