### ISSUE TITLE
Moving from travis-ci

### ISSUE THREAD

**Issue by stsewd** [prompt-toolkit/python-prompt-toolkit#1289]
Hi, since travis dropped the number of builders for open source projects, builds take too long to complete https://www.traviscistatus.com/#month.

Would you agree on moving to github actions or something else? I can help sending a PR if that's the case :)

**Comment by jonathanslenders** [comment]
Yes, I that would be good. I think GitHub actions is fine. (I've never used it personally though.) Thanks!
