### ISSUE TITLE
Documentation still lists six as required

### ISSUE THREAD

**Issue by septatrix** [prompt-toolkit/python-prompt-toolkit#1301]
The documentation still lists `six` as a requirement however it does not seem to be imported anymore.

PS: Additionally this library needs pygments but it is not listed in the requirements - is that an oversight or is there a reason for it?

**Comment by MrMino** [comment]
Might be related to #1276.

**Comment by jonathanslenders** [comment]
Pygments is an optional dependency. It's only required in case of a Pygments lexer.
