### ISSUE TITLE
ImportError: circular import

### ISSUE THREAD

**Issue by mherke** [prompt-toolkit/python-prompt-toolkit#1368]
Hi i am new to python-prompt-toolkit and get an issue with this simple example:

enviroment:
---------------------------
python: 3.9.1
prompt-toolkit: 3.0.8

coding:
---------------------------
from prompt_toolkit import prompt as p

if __name__ == '__main__':
    answer = prompt('Give me some input: ')
    print('You said: %s' % answer)

error message:
---------------------------
Traceback (most recent call last):
  File "D:\Programmierung\Python\test\prompt_toolkit.py", line 1, in <module>
    from prompt_toolkit import prompt as p
  File "D:\Programmierung\Python\test\prompt_toolkit.py", line 1, in <module>
    from prompt_toolkit import prompt as p
ImportError: cannot import name 'prompt' from partially initialized module 'prompt_toolkit' (most likely due to a circular import) (D:\Programmierung\Python\test\prompt_toolkit.py)

it would be kind if someone can point me to my coding error or present a solution for the issue.

with kind regards

michael

**Comment by jonathanslenders** [comment]
Hi Michael,

Can you rename your own script and try again? Don't call something prompt_toolkit.py please.

Jonathan

**Comment by mherke** [comment]
Hi Jonathan,

i renamed my script and guess what? no more errors. 

many thanks for your quick support.
