### ISSUE TITLE
Question: how to force (another) buffer to show output without waiting for the input handler to finish?

### ISSUE THREAD

**Issue by scorchio** [prompt-toolkit/python-prompt-toolkit#1402]
Hi,

I'm working on a small project using prompt_toolkit and I wanted to write into a `Buffer` in a `Window`'s `BufferControl` from another `TextArea`'s `accept_handler`, but I noticed that if there's a long running operation in the accept handler, I won't be able to see the output before that finishes. In the following example, I would assume that I could see the "Got some input" text before the 10 s passes, but it doesn't happen that way:

```py
from time import sleep

from prompt_toolkit import Application
from prompt_toolkit.buffer import Buffer
from prompt_toolkit.key_binding import KeyBindings
from prompt_toolkit.layout import BufferControl, HSplit, Layout, Window
from prompt_toolkit.widgets import TextArea


def input_accept_handler(buff):
    output_buffer.insert_text("Got some input\n")
    sleep(10)
    return False


if __name__ == "__main__":
    input_field = TextArea(
        prompt=">>> ",
        accept_handler=input_accept_handler,
        multiline=False,
    )
    output_buffer = Buffer()
    root_container = HSplit(
        [
            Window(
                content=BufferControl(buffer=output_buffer),
            ),
            input_field,
        ]
    )

    bindings = KeyBindings()

    @bindings.add("c-q")
    def exit_(event):
        event.app.exit()

    app = Application(
        full_screen=True,
        layout=Layout(root_container, focused_element=input_field),
        key_bindings=bindings,
    )
    app.run()
```

Is there anything that I could do to force the `output_buffer` to show the updated content before the `sleep()` starts?

**Comment by MrMino** [comment]
I think you might want to learn / utilize `asyncio` here. `Application` runs on `asyncio`. You might want to have a coroutine (a trampoline) in the background that updates `ouptut_buffer` periodically, and reschedules itself onto the event loop.

**Comment by scorchio** [comment]
Yeah - I admit I had to spend some thing learning the basics of `asyncio` to have a clue about where to get started. What caused me the problem originally was that I had no idea how to start working with async calls in the input handler, but using `asyncio.create_task()` inside the handler, I could solve the problem. ([This article](https://hynek.me/articles/waiting-in-asyncio/) helped me.)
