### ISSUE TITLE
python prompt_toolkit arrow key navigation

### ISSUE THREAD

**Issue by Justaus3r** [prompt-toolkit/python-prompt-toolkit#1411]
My question is that after importing prompt-toolkit ,I am unable to use the arrow keys(up , down) for navigation(of previously entered command). I am running an infinite loop inside which I am taking input using the prompt method .is this a bug in python-prompt-toolkit or is there a way to achieve this. I would be glad if someone could shed some light on this problem

**Comment by furadnik** [comment]
https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#history

**Comment by Justaus3r** [comment]
i see. ty for the update
