### ISSUE TITLE
Strikethrough text attribute

### ISSUE THREAD

**Issue by sphh** [prompt-toolkit/python-prompt-toolkit#1416]
It looks that more and more (Linux) terminals support the strike through effect (it can be tested with `echo -e "\e[9mtest\e[0m"`), so I think, it would be great, if the `prompt-toolkit` can support this! Would that be feasible?

**Comment by jonathanslenders** [comment]
That sounds nice.

Feel free to create a pull request for this if you have some time.

Search for "bold" or "underline" in the code base, and do similar stuff for this. Maybe call it "strike", like the old HTML tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike (CSS calls it line-through).

**Comment by sphh** [comment]
I gave it a quick try: I searched for `underline` and added similar lines for `strike`, but now I get the following exception:
```python3
[...]
    prompt_toolkit.print_formatted_text(
  File "/usr/local/lib/python3.8/dist-packages/prompt_toolkit/shortcuts/utils.py", line 128, in print_formatted_text
    renderer_print_formatted_text(
  File "/usr/local/lib/python3.8/dist-packages/prompt_toolkit/renderer.py", line 782, in print_formatted_text
    output.set_attributes(attrs, color_depth)
  File "/usr/local/lib/python3.8/dist-packages/prompt_toolkit/output/vt100.py", line 599, in set_attributes
    self.write_raw(escape_code_cache[attrs])
  File "/usr/local/lib/python3.8/dist-packages/prompt_toolkit/output/vt100.py", line 282, in __missing__
    fgcolor, bgcolor, bold, underline, italic, blink, reverse, hidden = attrs
ValueError: too many values to unpack (expected 8)
```

I guess it would be quicker for everybody, if someone familiar with the code adds this feature!

Here is some technical background I researched:

### ANSI codes
(https://en.wikipedia.org/wiki/ANSI_escape_code#SGR)

**9** 	Crossed-out, or strike 	Characters legible but marked as if for deletion.
**29** 	Not crossed out

### HTML codes
(https://en.wikipedia.org/wiki/Strikethrough#HTML)

**`<del>`** tag, a semantic element representing deleted text, which user agents (typically web browsers) often render as a strikethrough

In `prompt-toolkit` this could be represented either as `s`/`strikethrough` or possibly as `d`/`delete`.

**Comment by burningfireplace** [comment]
> ```python
> File "/usr/local/lib/python3.8/dist-packages/prompt_toolkit/output/vt100.py", line 282, in __missing__
>     fgcolor, bgcolor, bold, underline, italic, blink, reverse, hidden = attrs
> ```

It looks like you forgot to add it to the line which throws the exception. 

`fgcolor, bgcolor, bold, underline, italic, blink, reverse, hidden,` **strikethrough**  `= attrs`

I'm not familiar with the codebase and didn't look much further into it but you'll probably also want to add something like this to the same method:

```
if strikethrough:
    parts.append("9")
````

IMHO: `<s>...</s>` for the HTML tags and `strikethrough` for the style attribute makes the most sense because `del` is too specific for this use case.

**Comment by sphh** [comment]
Thanks @burningfireplace for spotting this stupid mistake: I added `strike` to the docstring, but not to the `vt100.py` code (but I did it right in `win32.py` …)

There is now a PR implementing this: #1446.

Since I do not want to enter the `<bold>` vs. `<strong>` war, so I added the following tags: `<strike>`, `<s>` and `<del>` as it is done with `<bold>`.
