### ISSUE TITLE
pygments is missing as a dependency

### ISSUE THREAD

**Issue by ironbars** [prompt-toolkit/python-prompt-toolkit#1431]
Hello,

In the documentation, pygments is listed as a dependency, but it is not present in setup.py.  Thus, installing prompt-toolkit from PyPI (by any method) doesn't grab it.  Not sure if this is by design (i.e. the preference would be for users to install pygments themselves), but I thought I would let you know.

Let me know if you need any more information.

-Marc

**Comment by jonathanslenders** [comment]
This is by design. Pygments is an optional dependency. prompt_toolkit works fine without Pygments, as long as no pygments-based syntax highlighting is used. Maybe this should be made more clear in the documentation.

**Comment by ironbars** [comment]
OK, thank you for the information!
