### ISSUE TITLE
is it possible to show all the options for the same level of nested-completer?

### ISSUE THREAD

**Issue by dickens88** [prompt-toolkit/python-prompt-toolkit#1451]
Hi,  I had a `NestedCompleter` like this:
```
completer = NestedCompleter.from_nested_dict({
    'iam': {
        'show': None,
        'new_user': {'username=', 'password='}
    },
    'exit': None,
})
```
what i want is to let user run a command to create new user. to create user, one need to type in `username` and `password`. when i type in `iam new_user`  and press `tab`, the auto completer works find, it will looks like this:
![image](https://user-images.githubusercontent.com/8390209/123993358-f3cab200-d9fe-11eb-95be-6120e02f1f41.png)
but when i typed `iam new_user username=123`, the password menu is gone ... from my view, the `username` and `password` are at the same level of the nested-completer. so is it possible to show `password` option when the `username` is already typed?

**Comment by MrHallway0** [comment]
You could use `WordCompleter` or something like this:
```
completer = NestedCompleter.from_nested_dict({
    'iam': {
        'show': None,
        'new_user': {'username=', 'password='},
        'username=': {'password='},
        'password=': {'username='}
    },
    'exit': None,
})
```
It doesn't look good but it should work.

**Comment by dickens88** [comment]
@MrHallway0 Thank you so much for you quick reply. 

it works, but if the options are more, it will be very ugly ... for example
```
iam new_user username=abc password=xxx region=123 flag=456
```
Generally, these options can only appear once, that is, they cannot be repeated. so that if i use `WordCompleter` is there a way to avoid repeated completion?

**Comment by MrHallway0** [comment]
Sadly, it would appear, that [`WordCompleter`](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/completion/word_completer.py#L12) only takes one argument.
