### ISSUE TITLE
How can I use the tab key as a input for four spaces? 

### ISSUE THREAD

**Issue by MrHallway0** [prompt-toolkit/python-prompt-toolkit#1452]
Instead of having the tab key trigger autocomplete how could I instead use it to add four spaces to a multi-line input?

**Comment by erasels** [comment]
You can just create a keybind like so:
`
from prompt_toolkit.shortcuts import prompt
from prompt_toolkit.keys import Keys
import prompt_toolkit.buffer

kb = KeyBindings()

@kb.add(Keys.Tab)
def _(event):
    buff: prompt_toolkit.buffer.Buffer = event.app.current_buffer
    buff.insert_text("    ")


prompt("Input: ", key_bindings=kb)`

**Comment by MrHallway0** [comment]
Thank you @erasels!
