### ISSUE TITLE
This might be a bug or my mistake but here it is

### ISSUE THREAD

**Issue by xcodz-dot** [prompt-toolkit/python-prompt-toolkit#1454]
I have been trying to use prompt toolkit using the following example:

```python
from pygments.lexer import RegexLexer
from pygments.token import *

class CalculatorLexer(RegexLexer):
    name = 'Calculator'

    tokens = {
        'root': [
            (r"[\+\-\/\*\(\)\%\^]", Operator),  # All the single character operators
            (r"\d*\.\d*", Number.Float),  # A Decimal
            (r"\d*", Number.Integer),  # A Integer
            (r".*", Text)  # Any Other Thing
        ]
    }

from prompt_toolkit.shortcuts import prompt
from prompt_toolkit.lexers import PygmentsLexer

text = prompt('Enter HTML: ', lexer=PygmentsLexer(CalculatorLexer()))
print('You said: %s' % text)
```

but it always raises this error:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    text = prompt('Enter HTML: ', lexer=PygmentsLexer(CalculatorLexer()))
  File "/home/xcodz/.local/lib/python3.8/site-packages/prompt_toolkit/lexers/pygments.py", line 197, in __init__
    self.pygments_lexer = pygments_lexer_cls(
TypeError: 'CalculatorLexer' object is not callable
```

At first I thought that I am not supposed to call the custom lexer class that I created. but if I do not initialise my custom class, the program does nothing and instantly RAM usage starts rising. My Computer have crashed 2 times because of this behaviour.

Here is what happens after I start and kill the process of the program:

![image](https://user-images.githubusercontent.com/71920621/124374476-27386580-dcb9-11eb-940f-4d390120278d.png)

**Comment by jonathanslenders** [comment]
The parentheses after ``CalculatorLexer`` have to be removed.

```python
text = prompt('Enter HTML: ', lexer=PygmentsLexer(CalculatorLexer))
```

If this freezes the process and memory goes up, then it's probably a bug in any of the regular expressions.
I think the patterns have to match strings of at least length 1, so ``.*`` should be ``.+`` for instance.

This works for me:
```python
    tokens = {
        'root': [
            (r"[\+\-\/\*\(\)\%\^]", Operator),  # All the single character operators
            (r"\d*\.\d*", Number.Float),  # A Decimal
            (r"\d+", Number.Integer),  # A Integer
            (r".+", Text)  # Any Other Thing
        ]
    }
```

**Comment by xcodz-dot** [comment]
And yeah it was regular expression problem.

nevermind, instead of using pygments I created my own prompt-toolkit based Lexer and I have it in my answer on [this](https://stackoverflow.com/questions/68241694/how-to-colourise-user-input-in-python/68241783#68241783) stackoverflow post. It was certainly a bumpy ride to create my own lexer from scratch but it worked. :grin:
