### ISSUE TITLE
[typo] remove should be remove_binding.

### ISSUE THREAD

**Issue by Freed-Wu** [prompt-toolkit/python-prompt-toolkit#1501]
In <https://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.key_binding.KeyBindings.remove_binding>,

```
remove_binding(*args) → None

    Remove a key binding.

    This expects either a function that was given to add method as parameter or a sequence of key bindings.

    Raises ValueError when no bindings was found.

    Usage:

    remove(handler)  # Pass handler.
    remove('c-x', 'c-a')  # Or pass the key bindings.
```

In usage, `remove` should be `remove_binding`.

**Comment by veni-vidi-code** [comment]
I dont think this is a typo. remove_binding is just there for backwardscompatibility and should not be used. It is set via `remove_binding = remove` and by that it just copies the docs of remove with its usage cases.

**Comment by Freed-Wu** [comment]
I see, thanks!
