### ISSUE TITLE
Make layout components all inherit from a base class SO THAT I keep my type checker happy

### ISSUE THREAD

**Issue by jftsang** [prompt-toolkit/python-prompt-toolkit#1533]
I've got something like
```python
fields = {'foo': TextArea(...), 'bar': TextArea(...)}
dialog_body = HSplit(
        [
            Label(...)
        ] + [
            VSplit([
                Label(text=field_name),
                field
            ])
            for field_name, field in fields.items()
        ] + [
            ValidationToolbar(),
        ],
        padding = D(preferred=1, max=1)
    )
dialog = Dialog(..., body=dialog_body)
```
This makes PyCharm's type checker unhappy since I am adding lists of different types (e.g. `List[Label]` plus `List[VSplit]`). Currently, classes like `Label` and `TextArea` do not inherit from any other class. If they did, then a type inference system would be able to tell that the list addition is valid.

**Comment by jonathanslenders** [comment]
I'm not sure this will solve anything. All these components already inherit from a common base class, which is called... ``object``...

What you want to to build a list of type ``list[prompt_toolkit.layout.AnyContainer]``.
