### ISSUE TITLE
SIGINT like pressing control-c

### ISSUE THREAD

**Issue by anki-code** [prompt-toolkit/python-prompt-toolkit#1537]
_Originally posted by @jonathanslenders in https://github.com/xonsh/xonsh/issues/3628#issuecomment-990296089_:

> If I recall correctly, prompt_toolkit does not set any signal handlers, because potentially it runs in a different thread (where setting signal handlers doesn't work in Python). However, it handles control-c by setting the terminal in raw mode and reading control-c literally from the input.
> Would you like an external SIGINT to behave exactly like pressing control-c?
> (assuming prompt_toolkit does run in the main thread.)
> If so, feel free to open a issue in the prompt_toolkit issue tracker. That way I won't forget.

**Comment by jonathanslenders** [comment]
Possible fix: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1538 (Not yet tested extensively.)

**Comment by jonathanslenders** [comment]
Closing this issue. That fix was merged and released.
