### ISSUE TITLE
3.0.25 introduced change that breaks ipython 8.1 on windows 10

### ISSUE THREAD

**Issue by franzhaas** [prompt-toolkit/python-prompt-toolkit#1553]
Dear all,

it apears that in the release of 3.0.25 a change was introduced that uses async functionality which is not available on my windows 10 python 3.10 and python 3.9.

See also.:

https://github.com/ipython/ipython/issues/13494

![image](https://user-images.githubusercontent.com/11477153/151407494-577be56a-a213-4eef-9faf-34f46b3ff868.png)

Thanks in advance,
Franz

**Comment by jonathanslenders** [comment]
Wow, thanks for pointing out this issue! I'll fix it today and push a new release asap!

**Comment by jonathanslenders** [comment]
Would you be able to try this commit and see whether it's fixed now: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1554 ?Then I push a new release.

**Comment by jonathanslenders** [comment]
I pushed 3.0.26. It should work now. Thanks a lot for creating the issue!

**Comment by rsokl** [comment]
Typically how long does it take for the conda-forge feedstock to get updated? I have about 1,500 high school students (that's not a typo, seriously 1,500) beginning an online course next week, and am wondering how many of them will hit this (they use `conda` in the course).

I was just testing our "getting started" course materials, and hit this.

**Comment by jonathanslenders** [comment]
Hi @rsokl, honestly I don't know how/when conda-forge updates packages, or who's responsible for that. Looks like the 3.0.25 version was already picked up earlier today, but 3.0.26 not yet.
https://anaconda.org/conda-forge/prompt_toolkit

**Comment by jonathanslenders** [comment]
@scopatz : Do you know how/when Conda packages are published? The latest version I see at conda-forge is broken right now for Windows users.

/cc @jakirkham, @staticdev, @melund

**Comment by franzhaas** [comment]
Thanks, this works for me.

Amazing reaction time!

Best regards,
Franz

**Comment by jakirkham** [comment]
> @scopatz : Do you know how/when Conda packages are published? The latest version I see at conda-forge is broken right now for Windows users.
> 
> /cc @jakirkham, @staticdev, @melund

It looks like @ocefpaf just recently merged this ( https://github.com/conda-forge/prompt_toolkit-feedstock/pull/69 )

Should add we are happy to add others to that feedstock if that is helpful 🙂

**Comment by ocefpaf** [comment]
We should also mark the other build as broken. I'll try to address it later today, unless someone beats me to it. Thanks all!
