### ISSUE TITLE
How to get transparent or no background color for bottom_toolbar

### ISSUE THREAD

**Issue by GhostOps77** [prompt-toolkit/python-prompt-toolkit#1767]
I'm just using the `bottom_toolbar` attribute in the `PromptSession` class to generate bottom bar, and by default, it displays text in white background.

I used `HTML` class to change the background color of the bottom toolbar, but I can't make the background to be transparent. (I mean, the text background should match the same as with my terminal). But as far as I've seen, I can't anything related to that at all.

So, is there anyway where I can get transparent bg for `bottom_toolbar`?

**Comment by joouha** [comment]
You need to pass a `Style` to your `PromptSession` defining the background-color for the `bottom-toolbar` class.

Have a look at the [`bottom-toolbar.py` example](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/490cf900188df357611cdc9358256be0e5ce2e16/examples/prompts/bottom-toolbar.py#L51-L58).

The default `bottom-toolbar` class sets `reverse`, so you'll need to add `no-reverse` to your style definition to remove the white background:

```python
from prompt_toolkit import prompt
from prompt_toolkit.styles import Style

style = Style.from_dict({"bottom-toolbar": "fg:lightblue bg:default noreverse"})
prompt("Input: ", bottom_toolbar="This is a toolbar", style=style)
```

![image](https://github.com/prompt-toolkit/python-prompt-toolkit/assets/12154190/6d606797-f2e8-4b48-a31a-e5b09f83e8a8)

**Comment by GhostOps77** [comment]
Thanks! That worked!
Closing this issue now
