### ISSUE TITLE
Is it possible to make the strikethrough lines a little bit thicker?

### ISSUE THREAD

**Issue by GhostOps77** [prompt-toolkit/python-prompt-toolkit#1768]
This is a very good utility. I like to play with it all the time.
but while doing that, i feel like the strikethrough lines in the strikethrough text is very thin.
(I'm using `HTML` class to format the text output)

So, is there anyway to increase the thickness of this line?

Is this what actually available, or is this an intentional feature?

and by the way, im using win11, and prompt-toolkit v3.0.38
![Screenshot (81)](https://github.com/prompt-toolkit/python-prompt-toolkit/assets/72981180/068d93f5-5dc1-43e1-b6c0-36fb0b9b3d51)

**Comment by kylepollina** [comment]
AFAIK that is entirely controlled by the font and not controlled by the library. If you change your terminal font it will do that. The library can not support how fonts are rendered

**Comment by joouha** [comment]
In [`WezTerm`](https://wezfurlong.org/wezterm) you can configure this by setting the [`underline_thickness`](https://wezfurlong.org/wezterm/config/lua/config/underline_thickness.html) parameter in your configuration

![image](https://github.com/prompt-toolkit/python-prompt-toolkit/assets/12154190/52b19929-b47e-4184-94de-2b8e4e3a2efe)

**Comment by GhostOps77** [comment]
ok, got it.
so, it's based on terminal's font type.
