### ISSUE TITLE
cmder link goes to shady site

### ISSUE THREAD

**Issue by jwodder** [prompt-toolkit/python-prompt-toolkit#1816]
The "cmder" link under ["About Windows support" in the README][1] goes to https://cmder.net, a site dedicated to trying to sell you gold.  I do not believe this is where you meant for this link to go.  I don't know if the link originally went where you intended but the domain later lapsed and was gobbled up, or if you were listing the wrong link from the beginning, but either way the current link needs to go.

[1]: https://github.com/prompt-toolkit/python-prompt-toolkit#about-windows-support

**Comment by jonathanslenders** [comment]
I guess the domain was taken over at some point. I didn't pay attention. Thanks for the MR!
