### ISSUE TITLE
How do I use NumberredMargin?

### ISSUE THREAD

**Issue by LoganDark** [prompt-toolkit/python-prompt-toolkit#443]
https://github.com/jonathanslenders/python-prompt-toolkit/blob/59328630597daa813192b81365bc4132a859b2d6/prompt_toolkit/layout/margins.py#L60-L118

The prompt function doesn't seem to accept a custom margin and get_continuation_tokens doesn't get passed any parameters hinting at the line number

**Comment by jonathanslenders** [comment]
Hi @LoganDark,
This is unfortunately a limitation of the APi that ``prompt_toolkit.shortcuts`` exposes. There is indeed no way to use it right now.
It is of course possible to build the whole layout of the application yourself, just like ptpython does, but these are all internal APIs which are much more prone to change. In fact, I'm planning to refactor a part of the internal architecture right now. So, it's difficult to give suggestions/support for things like ``NumberredMargin`` right now.

**Comment by LoganDark** [comment]
Closing this issue since I don't use Python anymore. Feel free to reopen if this is still something you're interested in supporting.
