### ISSUE TITLE
How to implement a lexer

### ISSUE THREAD

**Issue by czhang03** [prompt-toolkit/python-prompt-toolkit#471]
http://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.layout.lexers.Lexer

Here it says it takes a `document` and convert it into `tokens`.
I know the data structure of document, but what is the data structure of a token?

for example I have 3 types of token: `command`, `parameter_name`, and `parameter_value` 
What should I return?

**Comment by shikukuya** [comment]
#1463
