### ISSUE TITLE
create_prompt_application missing from 2.x

### ISSUE THREAD

**Issue by ibeex** [prompt-toolkit/python-prompt-toolkit#647]
```python
>>> prompt_toolkit.__version__
'2.0.3'
>>> from prompt_toolkit.shortcuts import create_prompt_application
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'create_prompt_application'
```
ipython and lots off other apps don't work any more.

**Comment by jonathanslenders** [comment]
Hi @ibeex,

IPython does indeed not yet run on prompt_toolkit 2.0. They're working hard on that.
See this issue: https://github.com/ipython/ipython/pull/11177

If you have some time available, it would be great if you could help them testing the latest IPython version from GitHub.

**Comment by techtonik** [comment]
IPython merged, but is there a porting guide for all other apps?

**Comment by jonathanslenders** [comment]
There is: https://python-prompt-toolkit.readthedocs.io/en/2.0/pages/upgrading.html
It's probably not complete, but let me know if you think something important is missing.

**Comment by ProbonoBonobo** [comment]
For anyone needing a temporary workaround, I can confirm that reverting to v.1.x mostly resolves the errors that prevent ipython, ptpython, etc. from initializing:

```

git clone -b 1.0  --single-branch https://github.com/jonathanslenders/python-prompt-toolkit.git
cd python-prompt-toolkit
python3 setup.py install
```


You get the following error when launching ptpython if you're using the [default `config.py` template](https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py)...

```
~/dev/git/clones/python-prompt-toolkit$ ptpython
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.6/site-packages/ptpython/repl.py", line 244, in run_config
    six.exec_(code, namespace, namespace)
  File "/home/kevin/.ptpython/config.py", line 8, in <module>
    from prompt_toolkit.key_binding.key_processor import KeyPress
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.key_processor'

```
...but it's not fatal, and can be safely ignored, or you could delete the offending lines. A quick glance at the code suggests KeyPress is only used to map the 'jj' key sequence to 'Esc' in vim mode.

**Comment by gpotter2** [comment]
I think this issue could be closed :)

**Comment by jonathanslenders** [comment]
Ok, closing it. Feel free to open again if needed.
