### ISSUE TITLE
Cursor jump to the beginning of line

### ISSUE THREAD

**Issue by zzl0** [prompt-toolkit/python-prompt-toolkit#658]
## Description

If you are using `SqliteConsoleLexer` and when you start to type, text will disappear and cursor will jump to beginning of line.

## How to reproduce it?

``` python
# sqlitecli.py
from __future__ import unicode_literals
from prompt_toolkit import PromptSession
from prompt_toolkit.lexers import PygmentsLexer
from pygments.lexers import SqliteConsoleLexer

def main():
    session = PromptSession(lexer=PygmentsLexer(SqliteConsoleLexer))

    while True:
        try:
            text = session.prompt('> ')
        except KeyboardInterrupt:
            continue
        except EOFError:
            break
        else:
            print('You entered:', text)
    print('GoodBye!')

if __name__ == '__main__':
    main()
```

#### steps

``` bash
$ pipenv install prompt_toolkit==2.0.3
$ pipenv install pygments
$ pipenv run python sqlitecli.py
```

**Comment by jonathanslenders** [comment]
@zzl0,

Thank you for reporting this issue and creating the pull request!
I consider this a bug in Pygments, but it's indeed good to log a warning. I'll have a look at the merge request ASAP.

**Comment by zzl0** [comment]
@jonathanslenders 

Thanks, I agree it is a bug (not a feature) in `Pygments`. I didn't find a test file for `prompt_toolkit.lexers.pygments`, should I add a new test file and add unit test for change?

**Comment by zzl0** [comment]
close inactive issue.
