### ISSUE TITLE
prompt_toolkit on exit leaves terminal in bad state

### ISSUE THREAD

**Issue by mikegrobler** [prompt-toolkit/python-prompt-toolkit#661]
OnUbuntu 16.04 using Python 3.5 and prompt_toolkit 1.0.15.

Using librabry very simply in a python app:

import prompt_toolkit
...
while True:
    text = prompt_toolkit.prompt(prompt, history=FileHistory('sConsole.hst')).strip()
    ....

After the app terminates and returns to the terminal command prompt, the terminal does not echo any typing. Is there a way to force prompt_toolkit to terminate gracefully and in a known manner leaving the terminal as it was before invocation of the python app?

**Comment by lwm** [comment]
I was not able to reproduce the behaviour with your snippet that you are describing @mikegrobler.

For handling various ways of exiting gracefully, please refer to the examples:

> https://github.com/jonathanslenders/python-prompt-toolkit/tree/master/examples/prompts

**Comment by vlovich** [comment]
I have this problem too.  Is there a specific example you recommend?

**Comment by jonathanslenders** [comment]
@mikegrobler, @vlovich: Can you try using prompt_toolkit 2.0 instead?
I'm at least not able to reproduce it there, but not sure about 1.0.15.

**Comment by vlovich** [comment]
I never used anything other than 2.0

**Comment by vlovich** [comment]
my code is different than the original example and it's pretty complex and not shareable. Haven't tried finding a simpler repro case.

**Comment by vlovich** [comment]
Here's a simple repro case.  Run the program & hold the enter key (at least on OSX 10.13.6).

[test.txt](https://github.com/jonathanslenders/python-prompt-toolkit/files/2404007/test.txt)
