### ISSUE TITLE
Change content of container dynamically

### ISSUE THREAD

**Issue by sander76** [prompt-toolkit/python-prompt-toolkit#677]
Trying to figure out how to change the content of a container (filling it with a set of buttons) depending on a menu item choice.

I am going through the docs but I can't find how to do that.
I ran into `ConditionalContainer`. Is that what I should be using or there a better solution ?

Sander.

**Comment by lwm** [comment]
I believe the [ConditionalContainer](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#prompt_toolkit.layout.ConditionalContainer) is for conditionally hiding/showing the actual container, not configuring the contents of it. From any event handler (menu switch?), you should be able to access the properties of the container you want to change a set new values, no?

**Comment by jonathanslenders** [comment]
Hi @sander76,

There are two options here:

- Either replace the content on the parent container. Most containers support that. For instance, for a ``VSplit`` or ``HSplit``, you can manipulate the ``.children`` list. For a ``FloatContainer`` it is possible to change ``.content`` and ``.floats``. For some widgets like ``Frame`` it is also possible to change the content, by assigning to ``.body``. What is the parent container you have in mind?  (For some widgets, this doesn't work yet, but it's easy enough to make it work.)

- Use a ``DynamicContainer``. This takes a callable which should return whatever container is to be used as content.
