### ISSUE TITLE
CI: building the documentation with sphinx

### ISSUE THREAD

**Issue by decentral1se** [prompt-toolkit/python-prompt-toolkit#679]
Would you be interested in accepting a PR which builds the sphinx documentation?

We could also enable some linting there depending on how tight you want the ship to be ;)

I can pick it up if we're in agreement :+1:

**Comment by jonathanslenders** [comment]
Hi @lwm,
What would be the advantage over having readthedocs build the documentation like it works right now?

**Comment by lwm** [comment]
I think it would just be a way to know if your documentation was going to fail on RTD before it fails on RTD and instead blows up in the pull request check. RTD still builds and deploys your documentation there. It can be useful when messing around with the sphinx configuration, when/if it happens. Perhaps also to add checks for dead links and missing modules (for the reference pages).

**Comment by jonathanslenders** [comment]
Hi @lwm,
Yes, that sounds good. I remember there were still a couple of warnings when building the docs, I'm not sure whether we can fix that.

**Comment by asmeurer** [comment]
Building the docs on Travis is a good idea. I also recommend adding `html: SPHINXOPTS += -W` to the Makefile so that warnings are treated as errors (sometimes when Sphinx treats something as only a warning, ends up not being readable in the compiled docs, and sometimes it just removes it entirely).
