### ISSUE TITLE
FormattedTextControl with default_char

### ISSUE THREAD

**Issue by s4shyam95** [prompt-toolkit/python-prompt-toolkit#750]
The TokenListControl used to have this default_char param which it used for padding the text if there was extra space left. Since v2 where I believe TokenListControl was renamed to FormattedTextControl, this parameter is missing.
Is it expected of the user to already pass the 'text' param which is pre-padded ? Or is there another UIControl that you would recommend to be used to show a list of tokens?

**Comment by s4shyam95** [comment]
Also, I don't think that TokenListControl has been renamed to FormattedTextControl as the get_tokens argument used to be a callable returning a list of tuples. How can this behavior be replicated with a FormattedTextControl ?

Thanks for your help

**Comment by jonathanslenders** [comment]
Hi @s4shyam95,
The ``default_char`` option has been moved to the ``char`` option of the ``Window`` class.
``FormattedTextControl`` takes formatted text. This can always be a callable that returns formatted text.
It's explained over here: 
https://python-prompt-toolkit.readthedocs.io/en/master/pages/printing_text.html

**Comment by jonathanslenders** [comment]
Closing this. Feel free to open again, if the answer wasn't sufficient.
