### ISSUE TITLE
input_dialog.py example swallows ENTER

### ISSUE THREAD

**Issue by rofl0r** [prompt-toolkit/python-prompt-toolkit#763]
if you enter text, and press ENTER, the input will be deleted. if you use TAB instead to jump to the OK button, it will be preserved (same applies to password dialog example)

**Comment by jonathanslenders** [comment]
Hi @rofl0r,

Thank you for reporting. This is a new bug that was introduced. I fixed it here: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/b86db4bb1852f1fd56d23fb90586e6e73209db98

I'll do a new release soon.

Jonathan

**Comment by rofl0r** [comment]
thanks for the fix! closing, as the release is out already...
