### ISSUE TITLE
Confused about usage of Applications

### ISSUE THREAD

**Issue by martmists** [prompt-toolkit/python-prompt-toolkit#769]
For context, I'm working on an application that takes user input (using prompt_toolkit) and listens to a feed and prints it. This is all done using Asuncion, using a read/write socket pair.

The issue I experienced was that the print() calls sometimes filled in the text of the prompt, which I quite obviously wanted to avoid.

I looked into urwid, which I'd used before, but couldn't find a way to use it with prompt_toolkit.

Then I stumbled upon the Applications in the documentation, but I just couldn't figure out how to use them.

The concept is to have a box (urwid.LineBox) as main screen, with a scrollable list of commands executed and feed received.
Below that would be a small box for input, similar to what I currently use prompt() for.

Right now I'm wondering not only what elements I need to use, but also how I update them, how I get input, make users able to select from only the scrollable list, et cetera.

If you could give me some directions in how my code should look or what part of the documentation I should look, any related examples or even a project that has done this before, that would be greatly appreciated.

**Comment by sander76** [comment]
@martmists Did you have a look at the examples ?

https://github.com/prompt-toolkit/python-prompt-toolkit/tree/master/examples/full-screen

**Comment by martmists** [comment]
I did, but it was still too confusing to really understand how I'd implement my situation.

**Comment by martmists** [comment]
```
+--------------------------------+
| line two                       |
| line three                     |
| input: other line              |
| line five                      |
+--------------------------------+
| >> sample text                 |
+--------------------------------+
```
It would look roughly like this, with only the top box scrollable and selectable, whereas clicking in the input box would cause the cursor to move to that position. Currently I do not understand how to make this layout work on any terminal size, or even add text to a textbox for that matter. There are no examples that have a scrollable event log and a static input box, hence why I made this issue.

**Comment by sander76** [comment]
@martmists Not sure how I can help. If I can help at all. But I found checking the examples and try and solve each challenge one by one helped me out...

**Comment by martmists** [comment]
I got it to display, but it doesn't display any text that should display, and I am unable to type anything in the input field. Additionally, I am unable to scroll through the output window.

code:
```python
class MyClass(SomeBase):
    def __init__(self):
        super().__init__()

        self.output = TextArea(text="")

        self.input = TextArea(height=1, prompt=">> ",
                              multiline=False, wrap_lines=False,
                              accept_handler=self.accept,
                              auto_suggest=AutoSuggestFromHistory())

        self.app = Application(
            layout=Layout(
                container=HSplit([
                    Frame(self.output),
                    Frame(self.input)
                ]),
                focused_element=self.input,
            ),
            full_screen=True,
            mouse_support=True
        )

    def accept(self, _):
        self.log(f">> {self.input.text}")
        self.commands.append(self.input.text)

    def log(self, arg):
        text = self.output.text + "\n" + arg
        self.output.buffer = Document(text=text, cursor_position=len(text))  # Does not output anything

**Comment by sander76** [comment]
Remember this is a rather low-level framework.
If you want scrolling to work, you need to enable it.
If you want `Ctrl+C` to work you need to create a binding for it.

**Comment by martmists** [comment]
What about not being able to enter text? The application is started with
```py
async def start_ui(self):
    await self.app.run_async().to_asyncio_future()

async def start(self):
    asyncio.ensure_future(self.start_ui, loop=self.loop)
    await super().start()
```

**Comment by martmists** [comment]
Adding bindings for c-c and c-q did not change anything in behavior when trying to exit.
