### ISSUE TITLE
Python 3.6 and 3.7 support

### ISSUE THREAD

**Issue by blshkv** [prompt-toolkit/python-prompt-toolkit#778]
I noticed that this software does not support (officially) modern versions of Python,
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/setup.py#L49

Could you add it please?

Thanks

**Comment by jonathanslenders** [comment]
Done: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/a1fef6d56e6b644e38ccfd0dd207e2ddb1804f58

Thanks for opening the issue!
