### ISSUE TITLE
Refresh prompt from custom key binding 

### ISSUE THREAD

**Issue by ibeex** [prompt-toolkit/python-prompt-toolkit#788]
I am trying to oweride ctrl+d with custom command, calling command works but after presing c-d prompt and bottom toolbar are same. (commands.exit() changes prompt and bottom toolbar but) They change only if I pres enter, how can I redraw prompt and bottom toolbar from custom binding?

here is example code

``` python
def shell():
    """Repl shell"""
    print("Welcome")
    prompt = PromptSession(
        history=FileHistory(os.path.join(os.path.expanduser("~"), ".history.txt"))
    )
    commands = Commands()
    bindings = KeyBindings()

    @bindings.add("c-d")
    def _(event):
        def print_exit():
            print(commands.exit())

        run_in_terminal(print_exit)

    while True:
        try:
            user_input = prompt.prompt(
                commands.prompt,
                auto_suggest=AutoSuggestFromHistory(),
                enable_history_search=True,
                key_bindings=bindings,
                bottom_toolbar=commands.bottom,
            )
            if not user_input:
                continue
            except (EOFError, KeyboardInterrupt):
                break
```

**Comment by jonathanslenders** [comment]
I think the following should do it:
```python
from prompt_toolkit.application import get_app

get_app().invalidate()
```

**Comment by ibeex** [comment]
@jonathanslenders  this didn't worked I tried putting it in 
```python
    @bindings.add("c-d")
    def _(event):
        def print_exit():
            print(commands.exit())

        run_in_terminal(print_exit)
        get_app().invalidate()
```

but replacing `commands.prompt` and `bottom_toolbar` with functions works.

**Comment by jonathanslenders** [comment]
I'm closing this issue, given that you have a solution. Feel free to open again if needed.

**Comment by Zylvian** [comment]
Hey, what ended up being the solution here specifically?

I have a weird glitch with my autocompleter that makes the prompt look completely different from what it actually is.

Prompt shows:
https://i.imgur.com/UJdKz83.png

After finishing prompt:
https://i.imgur.com/wf6zStV.png

**Comment by deeuu** [comment]
I too would very much appreciate a concrete example of updating the prompt from a custom key binding!
