### ISSUE TITLE
Unexpected way to handle non-breakable space \xa0

### ISSUE THREAD

**Issue by zakora** [prompt-toolkit/python-prompt-toolkit#789]
I reported an issue against IPython recently (ipython/ipython#11490) due to a weird behavior, as can be seen on this gif:
![screencap](https://user-images.githubusercontent.com/106620/48313373-d5001e80-e5bb-11e8-9903-d26fd47c7447.gif)

**How to reproduce the bug:**
1. have a prompt managed by prompt_toolkit
2. insert the non-breakable space character (\xa0)

**What I expected:** A non-breakable space character appears
**Instead, what happens:** the `&` character appears on the screen

At first, I thought that the non-breakable space was replaced by `&` in my input. As it turns out, it is only the displayed character that is affected. As we can see on the gif above, the string variable still contains the non-breakable space after the prompt has processed the input, even if the input appears as `a = "&"`.

**Cause of the bug:** Digging into this bug, I found out that IPython was using prompt_toolkit to manage its prompt. Then, I found that prompt_toolkit explicitly converts the non-breakable space to `&`: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/05fc17b030ba3c49baf4539401aeca2910af0909/prompt_toolkit/layout/screen.py#L103
Apparently this was added in efdec6ea48e3e1a5a5095a170424ca5973df07f1, along with other character substitutions.

**Discussion:**
Reading a bit about this code, I think the intention is to transform some characters that are hard to read into readable ones. However, I find the substitution of `\xa0` into `&` not ideal since `&` is a common character that can be in an input.
Furthermore, the code mentions that the substitutions are based on vim: 
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/05fc17b030ba3c49baf4539401aeca2910af0909/prompt_toolkit/layout/screen.py#L68
but when I did some tests in vim, the non-breakable space doesn't appear as `&`.

Could you give me the bigger picture for the reason to replace `\xa0` with `&`? I might be missing some context to grasp the reason it was done this way.

In my case, seeing `&` instead of a space was really confusing. I understand the need to display special characters, maybe replacing it with `<nbsp>` or `<a0>` would have been less confusing for me.

**Comment by jonathanslenders** [comment]
Fixed here: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/7db93560cb1f10c96f4a22816774da63e67e467e

By default, we now render it like Emacs does. The style can be changed by styling the ``'nbsp'`` class.
Maybe in the future, we can also make the render text configurable.

**Comment by zakora** [comment]
Thanks for fixing this issue!

Confirmed to work as expected (yellow underlined space) by applying your patch.
