### ISSUE TITLE
Multi Threading with a single progress bar

### ISSUE THREAD

**Issue by makitos666** [prompt-toolkit/python-prompt-toolkit#794]
The documentation is a bit scarce, and I would like to know if you can make a single progress bar with parallel tasks.

I mean, is there any way to do something like: "update_pb (int i)"?
So I can have different threads, knowing in advance the total of iterations that I will do between all the threads and adding 1 to the variable "i" I can handle the bar.

Thanks!

**Comment by jonathanslenders** [comment]
Hi @makitos666,

Yes, this is possible. Have you seen this example for instance: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/progress-bar/many-parallel-tasks.py ?
