### ISSUE TITLE
tty issues when launching via docker compose

### ISSUE THREAD

**Issue by ashleyblackmore** [prompt-toolkit/python-prompt-toolkit#796]
Hi!

I'm trying to launch a script that uses prompt() from docker compose. With `tty = true` I get:
 ```
WARNING: your terminal doesn't support cursor position requests (CPR).
```

With 'tty = false`:

```
alert-blocks_1_e98bc44562b1 | Warning: Output is not to a terminal (fd=1).
alert-blocks_1_e98bc44562b1 | Warning: Input is not to a terminal (fd=0).
```

Do you know where I can get started on fixing this? It seems that the tty available from docker is not sufficient?

Thanks!

**Comment by bolshoydi** [comment]
the temporary solution is to use `run` instead of `up` , because  `docker-compose run` allocates  tty.

**Comment by ashleyblackmore** [comment]
Thanks @ashleyblackmore, that helped nicely, appreciate it. Should I close this issue?

**Comment by bolshoydi** [comment]
@ashleyblackmore Yes, I think you can close issue, becouse it's concerned more with `docker-compose` then with `prompt-toolkit` itself.
P.S.:
1. did you try  `stdin_open: true` option?
2. if you make docker-compose run don't forget then use `docker-compose down` to remove dockers

**Comment by indrajithi** [comment]
> the temporary solution is to use `run` instead of `up` , because `docker-compose run` allocates tty.

Have same issue when using `ipdb`. The above solution works but what is the permanent solution? 

I have set both :
```
    stdin_open: true
    tty: true
```
