### ISSUE TITLE
Drop python 2

### ISSUE THREAD

**Issue by imomaliev** [prompt-toolkit/python-prompt-toolkit#801]
I see that you had to delete type annotations in one of the latest commits, because they are not supported in python 2, what about dropping support for it? I think it would make it much easier for maintaining this project. Big projects like django already dropped support for python 2

**Comment by urain39** [comment]
Maybe, but not now.

**Comment by jonathanslenders** [comment]
Hi @imomaliev,

Yes, I've been thinking about it, but many prompt_toolkit users still require Python 2. The problem is that command line applications are often installed using the system Python installation, and often this is still Python 2.

At some point, we'll definitely drop Python 2 support. This would indeed make it possible to annotate all functions, but also to rewrite the core using native asyncio Futures and coroutines.

**Comment by imomaliev** [comment]
@jonathanslenders FYI https://pythonclock.org. I don't think now when python 2 EOL will be in year it is worth your effort. I wish there would be some kind of stat for prompt_toolkit to see exactly how many users currently on python 2, also since this pretty much new version and almost complete rewrite, I assume it is possible to direct python 2 users to use prompt_toolkit 1.x. But of course is completely up to you, but in my experience simpler code base also helps to invite contributors

**Comment by asmeurer** [comment]
You could release prompt-toolkit 2.1 that is Python 3-only, and maintain backports for important bugfixes for the Python 2-compatible 2.0. My view of Python 2 compatibility is that people who need it can always continue to use the older versions that still support it. After < 1 year they will already be doing this with the language itself.

It's a balance between on the one hand the opportunity cost of not being able to use Python 3-only features, and the cost of maintaining backports. Or you could not backport at all, which is easier for you, but then potentially a bug could cause issues for Python 2 users. 

So it's really up to you how badly you want Python 3 features. As a user it doesn't affect me, unless maybe the API changes to use async/await.

**Comment by mkurnikov** [comment]
> I wish there would be some kind of stat for prompt_toolkit to see exactly how many users currently on python 2

https://pypistats.org/packages/prompt-toolkit
~15% now.

**Comment by hugovk** [comment]
15% is very low!

Here's stats for some other projects, many of which have already or are soon dropping Python 2, and none are as low as 15%. 

https://dev.to/hugovk/python-version-share-over-time-4-26hm

**Comment by asmeurer** [comment]
Most prompt-toolkit users use it via another command line tool? How projects that use prompt-toolkit still even support Python 2? I know that IPython and xonsh, which are two of the more popular ones haven't supported Python 2 in a while (the Python 2 version of IPython doesn't even support prompt-toolkit 2.0, and xonsh has never supported Python 2).

**Comment by urain39** [comment]
Deleted, agreed with most one that it's time to drop Python 2.

**Comment by hugovk** [comment]
Please see PR https://github.com/prompt-toolkit/python-prompt-toolkit/pull/885.

**Comment by septatrix** [comment]
With prompt_toolkit 3 released this can now be closed
