### ISSUE TITLE
Automatic replacements

### ISSUE THREAD

**Issue by Aluriak** [prompt-toolkit/python-prompt-toolkit#807]
Hi !

I am building an interface, and wish to allow user to specify some mathematical symbols, either using some letters (like `u` in place of `∪`) or expression (\union).
I would like the prompt to replace any word matching the letter/expression by the mathematical symbol.

This can be emulated using a Completer subclass, but require user to push tab to get the symbol replaced. This is quite annoying.

Is there any way to get a real-time replacement of expressions, based on regexes or function rules ?

**Comment by asmeurer** [comment]
I don't know if it's the best way to do it, but you can add keybindings for "stop characters" (like space, `.`, and so on) that should trigger a replacement that checks if the previous token is a replacement, then replaces it (and also adds the stop character).

**Comment by jonathanslenders** [comment]
Indeed, there is this example: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/autocorrection.py

The alternative is to handle the ``on_text_insert`` event of the ``Buffer`` class. For a ``PromptSession``, you can use the ``pre_run`` callback to attach this event:

```python
def on_insert(buffer):
    ...  # In here, use the cursor position and text attributes and modify the buffer as you like.

def pre_run():
    session.default_buffer.on_text_insert += on_insert

session = prompt(pre_run=pre_run)
```

If you have a nice/useful/clean example use case, feel free to create a pull request to share it.

**Comment by Aluriak** [comment]
Cool, thank you for your responses :)

I will share my use case with pleasure ; expect a PR in the week !

**Comment by Aluriak** [comment]
Since the given example is very similar to my use case, i will not PR anything ; unless there is a real need for a similar example.
