### ISSUE TITLE
ImportError: cannot import name 'PromptSession' from 'prompt_toolkit'

### ISSUE THREAD

**Issue by c0r3dump3d** [prompt-toolkit/python-prompt-toolkit#809]
Hi, I'm trying to use prompt-toolkit but I have this error when I try to import some modules, for example with the PromptSession:

`from prompt_toolkit import PromptSession`

`ImportError: cannot import name 'PromptSession' from 'prompt_toolkit' (/usr/lib/python3.7/site-packages/prompt_toolkit/__init__.py)`

I have installed prompt-toolkit:

`pip install prompt_toolkit`

with python version 3.7.1:

`Python 3.7.1 (default, Oct 22 2018, 10:41:28)`

**Comment by c0r3dump3d** [comment]
I have found the error, I have a Arch Linux and previously I have installed python-prompt_toolkit version from pacman. I have uninstalled this version and installed again from pip, and it's working.

**Comment by DJDarkCyber** [comment]
`pip3 install prompt-toolkit==3.0.16`

**Comment by almurillo** [comment]
@c0r3dump3d I know this has been closed but I am in the same boat I cannot find a way to get the error to go away. How did you manage to uninstall the package. I had install it through conda command and I think that is my problem. I got rid off Anaconda completely but I am still having the same issue.

**Comment by almurillo** [comment]
@c0r3dump3d Thanks man. That's exactly what I did and also uninstall python and reinstall everything.
