### ISSUE TITLE
^M (control character) appears when provided as default to prompt

### ISSUE THREAD

**Issue by ashleyblackmore** [prompt-toolkit/python-prompt-toolkit#811]
When providing a string to the default param for prompt, i.e.,

```
s.prompt(message="in example below\r\n\r\n{code}\r\n")
```

The editable output explicitly displays the control char for a carriage return instead of the expected implicit carriage return:

```
in example below^M
^M
{code}^M
```

Is this a known issue? Is there a workaround for this? Normalizing the unicode before display doesn't appear to fix it.

Thanks!

**Comment by Queuecumber** [comment]
Did you fix this? I have a similar problem
