### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by shenxianpeng** [prompt-toolkit/python-prompt-toolkit#822]
python-prompt-toolkit/examples/prompts/auto-completion/autocomplete-with-control-space.py

line 3 `Eample of using the control-space key binding for auto completion.`

Eample should be Example

**Comment by shenxianpeng** [comment]
This is a issue of no consequence, I was just passing by, please close it any time. I am sorry if anyone's is inconvenience.

**Comment by jonathanslenders** [comment]
Fixed here: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/97240635dfb82b9aff9aa6ad45f84db23138b1cb
Thanks for pointing out!
