### ISSUE TITLE
Question: What is the difference between text_before_cursor and get_word_before_cursor?

### ISSUE THREAD

**Issue by tamago324** [prompt-toolkit/python-prompt-toolkit#823]
hi.

Thank you for a wonderful library!

Is there a difference between [document.text_before_cursor](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/81c30157422989957c8a56b333b17ba35ab1a223/prompt_toolkit/document.py#L155-L157) and [document.get_word_before_cursor()](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/81c30157422989957c8a56b333b17ba35ab1a223/prompt_toolkit/document.py#L410-L425)?

The difference is "contain" or "not contain" the leading space?

If there is a difference, I would like if there is an example

Thank you

**Comment by jonathanslenders** [comment]
Hi @tamago324,

``text_before_cursor`` is the whole text before the cursor, from the very first character until the cursor position.

``get_word_before_cursor`` returns the word before the cursor. Typically the part that would be removed by a ``Control-W`` key press in Vi mode (it's not exactly ``Meta+backspace`` in Emacs mode). if ``WORD=True`` is given, this will take any whitespace as a separator. A different regex pattern can be given in the latest release, if you want a different separator.

Hope this helps,
Jonathan

**Comment by tamago324** [comment]
Hi @jonathanslenders 

Thanks to you, I was able to understand the difference between them!

I am also very happy to understand the behavior about the WORD argument of `get_word_before_cursor`

Also, understanding has deepened by reading the source code [here](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/fc53fe9befbfdb86f6de0a2f4de14affb5d449b3/prompt_toolkit/document.py#L410-L455)(`get_word_before_cursor` and `find_start_of_previous_word `).

It was easy to understand that the same behavior as i_CTRL-W of vim was.

Thank you very much.
