### ISSUE TITLE
READLINE_LIKE completer behaves differently in 2.0.8 ? 

### ISSUE THREAD

**Issue by lambdamusic** [prompt-toolkit/python-prompt-toolkit#831]
Hello. I am using the fantastic autocomplete feature to build an [API REPL](https://github.com/lambdamusic/dimcli/blob/master/dimcli/console/repl.py#L224) and noticed that in version 2.0.8 if I hit TAB when no text prefix is present the autocomplete is not invoked. Eg

```
[1] Give some animals: # [TAB => shows all options]
alligator ape       bear      bee       butterfly chicken   dinosaur  dolphin   duck      elephant  goat      kangaroo  lion      rabbit    snake     turkey
ant       bat       beaver    bison     cat       crocodile dog       dove      eagle     fish      gorilla   leopard   mouse     rat       spider    turtle

[2] Give some animals: bear b # [TAB => shows options staring with b]
bat       bear      beaver    bee       bison     butterfly

[3] Give some animals: bear # [TAB => nothing shown!]
```

**NOTE** In version 2.0.7, the last example would show all available options. 

Am I doing anything wrong? Is there any way to revert back to the previous behaviour? 
Thanks a million in advance!

**Comment by jonathanslenders** [comment]
This looks like the same issue as https://github.com/prompt-toolkit/python-prompt-toolkit/issues/837

**Comment by lambdamusic** [comment]
Thanks for looking into this. I wish I could have been more helpful but still finding my way around prompt-toolkit

**Comment by jonathanslenders** [comment]
Hi @lambdamusic, can you check whether it's fixed now in the latest release?

**Comment by lambdamusic** [comment]
Thanks folks, works like a charm now.
