### ISSUE TITLE
print_formatted_text(ANSI(...)) removes color

### ISSUE THREAD

**Issue by RichardWarfield** [prompt-toolkit/python-prompt-toolkit#836]
While using prompt_toolkit with pygments to highlight Haskell code, I discovered that I get different output using `print_formatted_text(ANSI(ansi_string))` compared to `print(ansi_string)`

![bad_color](https://user-images.githubusercontent.com/4101168/52613249-22946c00-2ec8-11e9-850e-ca37bad4edbf.gif)

If I peek at the ANSI that gets output by the call to print_formatted_text, it is radically different from the input:

`'\x1b[0m\x1b[?7h\x1b[0m"\x1b[0mH\x1b[0me\x1b[0ml\x1b[0ml\x1b[0mo\x1b[0m \x1b[0mw\x1b[0mo\x1b[0mr\x1b[0ml\x1b[0md\x1b[0m"\x1b[0m\r\n\x1b[0m'`

**Comment by jonathanslenders** [comment]
Hi @RichardWarfield,

Thanks for reporting this bug! I think the following commit should solve it: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/327956a0e042a70a247fc43469559d6cdcd5060d
Can you try again?

**Comment by RichardWarfield** [comment]
That seems to fix it for me... thanks!

**Comment by jonathanslenders** [comment]
A new release has been published to PyPI with this fix.
