### ISSUE TITLE
completion of a line ending with a space in WordCompleter is broken in 2.0.8

### ISSUE THREAD

**Issue by jeroen-dhollander** [prompt-toolkit/python-prompt-toolkit#837]
In 2.0.8, completion of an input line like 'test ' is broken in the WordCompleter.

This can be seen with this simple test case:
```
def test_word_completer_static_word_list():
    completer = WordCompleter(['abc', 'def', 'aaa'])

    <snip current tests>

    # Multiple words ending with space. (Accept all options)
    completions = completer.get_completions(Document('test '), CompleteEvent())
    assert [c.text for c in completions] == ['abc', 'def', 'aaa']
```

After some digging I figured out it was broken by commit 81c30157.
I will publish a pull request with some extra unittests and the fix.

**Comment by jonathanslenders** [comment]
Thanks!

**Comment by jonathanslenders** [comment]
This looks indeed like a bug in ``prompt_toolkit.document.Document.get_word_before_cursor()``.

**Comment by jonathanslenders** [comment]
This was fixed.
