### ISSUE TITLE
Add KubeTerminal to "Projects using prompt_toolkit"

### ISSUE THREAD

**Issue by samisalkosuo** [prompt-toolkit/python-prompt-toolkit#842]
[KubeTerminal](https://github.com/samisalkosuo/kubeterminal) is a full screen application and uses prompt_toolkit.

**Comment by jonathanslenders** [comment]
Added here: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/8ed4aeea113cac2fdd478d900e59f48b8fa194a0
Nice project!
