### ISSUE TITLE
ImportError: cannot import name 'WordCompleter' from 'prompt_toolkit.contrib.completers'

### ISSUE THREAD

**Issue by Code4SAFrankie** [prompt-toolkit/python-prompt-toolkit#853]
I get the following error:

Traceback (most recent call last):
  File "e:\Work\Python\repl.py", line 4, in <module>
    from prompt_toolkit.contrib.completers import WordCompleter
ImportError: cannot import name 'WordCompleter' from 'prompt_toolkit.contrib.completers' (E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\contrib\completers\__init__.py)

when trying to run:

from prompt_toolkit import prompt
from prompt_toolkit.history import FileHistory
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
from prompt_toolkit.contrib.completers import WordCompleter
from pygments.lexers.sql import SqlLexer

SQLCompleter = WordCompleter(['SELECT', 'FROM', 'WHERE'], ignore_case = True)

while 1:
    inp = prompt(u'>',
        history = FileHistory('history.txt'),
        auto_suggest = AutoSuggestFromHistory(),
        completer = SQLCompleter,
        lexer = SqlLexer
    )
    print(inp)

on:

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

**Comment by devshawn** [comment]
Hi! Your import for `WordCompleter` is wrong. It should be:

```python
from prompt_toolkit.completion import WordCompleter
```

**Comment by Code4SAFrankie** [comment]
Thanks that fixed it
