### ISSUE TITLE
Multiple selection dialog

### ISSUE THREAD

**Issue by kislyuk** [prompt-toolkit/python-prompt-toolkit#856]
Thanks for building prompt-toolkit, it's an awesome package.

I'm trying to build a dialog to select multiple items from a list of items. It should look like this:

```
Select the widgets to send to the factory. Press Space or Enter to select:
[ ] Widget 1
[*] Widget 2
[ ] Widget 3
[ Send ] [ Quit ]
```

I haven't been able to find anything similar in the examples or docs. Is this possible? Thanks.

**Comment by gpotter2** [comment]
Feel free to checkout https://github.com/prompt-toolkit/python-prompt-toolkit/pull/889
