### ISSUE TITLE
Is it possible to cancel a prompt?

### ISSUE THREAD

**Issue by Verequies** [prompt-toolkit/python-prompt-toolkit#858]
I have an issue where when I lose connection to server, my program cleanly terminates, however the complete termination of the program is blocked till I press enter ( due to it being stuck in the input ). Normally once text has been entered, it would check if the connection is still alive before requesting another input.

Is it possible to cancel a prompt when it detects a variable change?

**Comment by jonathanslenders** [comment]
Hi @Verequies,

Yes, this is possible. Something like the following code should work. Can you give it a try?

```python
from prompt_toolkit.application import get_app
get_app().exit()
```

**Comment by Verequies** [comment]
Thanks heaps! I didn't do it quite that way as I'm not actually using the application. I did it using:

``
    import prompt_toolkit

    prompt = prompt_toolkit.PromptSession()

    # In some thread
    prompt.prompt('message: ')

    # In base thread, exit is called
    prompt.app.exit()
    
``

**Comment by jonathanslenders** [comment]
That looks even better, because you refer to the specific app instance in particular. It's better then calling get_app.

**Comment by Verequies** [comment]
Yep! That's the main reason I did it this way. Perhaps an example could be added to the documentationfor this implementation? 

Anyhow I'll close this issue now as its solved.
