### ISSUE TITLE
Add pattern to WordCompleter's constructor

### ISSUE THREAD

**Issue by ehsan-fj** [prompt-toolkit/python-prompt-toolkit#865]
Hi,

It might be a good idea to add `pattern` to WordCompleter's constructor in order to pass it to `document.get_word_before_cursor` in `get_completions` method.

Right now you have to override `get_completions`?!

**Comment by jonathanslenders** [comment]
This makes sense. Feel free to create a pull request, and I'll merge it.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/67e742de43c8fd41835be9d0ec06daafd4150e20
