### ISSUE TITLE
Posix pipe inputs might respond to CPR

### ISSUE THREAD

**Issue by vxgmichel** [prompt-toolkit/python-prompt-toolkit#876]
*Issue # 5 from [this gist](https://gist.github.com/vxgmichel/f99c372f05dafb16ab24960d985ba61a)*

It'd be nice to be able to configure whether a posix pipe input responds to CPR. It is currently forced to `False`:

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/9e3845abe9d3cd64c096eaba8d890943f86b8954/prompt_toolkit/input/posix_pipe.py#L39-L41

But this pipe might be connected to a vt100 terminal that supports ANSI codes. A good example of that is `TelnetConnection.vt100_input`:

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/9e3845abe9d3cd64c096eaba8d890943f86b8954/prompt_toolkit/contrib/telnet/server.py#L112

In this context `telnet_connection.vt100_input.responds_to_cpr` returns `False` even though CPR is most likely supported.

Also, all the tests seems to pass with `PosixPipeInput.responds_to_cpr` forced to `True` instead.

**Comment by jonathanslenders** [comment]
@vxgmichel: thanks for pointing out! I think you're right and this should be fixed. I think we can take a ``responds_to_cpr`` boolean input in ``PosixPipeInput`` that defaults to False.
