### ISSUE TITLE
Question: can I have  radiolist dialog where a user can select multi options?

### ISSUE THREAD

**Issue by unixsurfer** [prompt-toolkit/python-prompt-toolkit#890]
I need this https://github.com/CITGuru/PyInquirer#checkbox---type-checkbox. Is it possible? I checked the source code and I couldn't find it.
Thank you

**Comment by Leistungsabfall** [comment]
Why not use multiple `CheckBox` instances instead of a `RadioList`?

**Comment by unixsurfer** [comment]
Thanks for your fast reply. As far as I can see `CheckBox` it doesn't accept a list.

**Comment by gpotter2** [comment]
Feel free to checkout https://github.com/prompt-toolkit/python-prompt-toolkit/pull/889, which adds support for `CheckboxList`.

**Comment by unixsurfer** [comment]
I will check it out. I hope it will be merged and we will get a new release very soon.
