### ISSUE TITLE
Prompt_toolkit 3.0: full_screen defaulted to False

### ISSUE THREAD

**Issue by gpotter2** [prompt-toolkit/python-prompt-toolkit#895]
Hi !

Since 3.0, the shortcut dialogs don't start in full screen mode anymore

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/7b16d2401dc00e6dd82a565001de8b6f9a86af48/prompt_toolkit/shortcuts/dialogs.py#L257

If that's on purpose, it might be a good idea to document it somewhere (what would then be the recommended way ?)

(Great job with 3.0 ! :smile:)

**Comment by gpotter2** [comment]
Fixed in https://github.com/prompt-toolkit/python-prompt-toolkit/commit/f4e1f200e9bcc95bc07415350b40eb8985163a25

**Comment by jonathanslenders** [comment]
Thank you for reporting the issue @gpotter2!
I forgot to respond to this issue when fixing it.

**Comment by gpotter2** [comment]
Thanks for the answer :smile:

What's your plan with 3.0 (are there still stuff you're willing to add / any guess on when it will be released/pre-released ?)

For instance, it is said in the CHANGELOG that you changed how `patch_stdout` behave, but I can't find a trace of such changes :/
