### ISSUE TITLE
button_dialog example AttributeError

### ISSUE THREAD

**Issue by OphirCarmi** [prompt-toolkit/python-prompt-toolkit#907]
Traceback (most recent call last):
  File "scratch_46.py", line 23, in <module>
    main()
  File "scratch_46.py", line 15, in main
    ('Maybe...', None),
AttributeError: 'bool' object has no attribute 'run'

need to remove ".run()"

**Comment by jonathanslenders** [comment]
Hi @OphirCarmi,

As pointed out in the PR, the ``run()`` call is only required in prompt_toolkit 3.0, which is not yet released. Check the 2.0 branch for examples for prompt_toolkit 2.0.

**Comment by OphirCarmi** [comment]
Ok, thanks for your quick reply.
