### ISSUE TITLE
Anchor tag is not displaying in terminal using HTML class

### ISSUE THREAD

**Issue by jawahar273** [prompt-toolkit/python-prompt-toolkit#925]
Hi I have been building TUI app which simply display the html when I parse the html file and display the value in the terminal to my surprise the anchor tag are missing from the parse value.

**Comment by jonathanslenders** [comment]
Hi @jawahar273,

If you are using ``prompt_toolkit.formatted_text.HTML``, this only supports a subset of HTML, like ``<strong>/<bold>``, ``<em>/<i>``, etc... see: https://python-prompt-toolkit.readthedocs.io/en/master/pages/printing_text.html#html

There is no way to render a hyperlink to the terminal, unfortunately. (As far as I'm aware, terminals don't support that.)

**Comment by jawahar273** [comment]
Hi @jonathanslenders 
is it possible to use simple custom tag(or like web component etc...) for handling anchor tag in displaying to the terminal..
