### ISSUE TITLE
Add pydoro project lists

### ISSUE THREAD

**Issue by JaDogg** [prompt-toolkit/python-prompt-toolkit#926]
pydoro is a tomato/pomodoro timer in the terminal.

I'm using prompt-toolkit for the TUI ✔

Github: https://github.com/JaDogg/pydoro
ASCII Cast: https://asciinema.org/a/251825

**Comment by JaDogg** [comment]
@drunkwcodes why the thumbs down 😢

**Comment by drunkwcodes** [comment]
Timer is not a good use case for `prompt-toolkit`.

**Comment by JaDogg** [comment]
@drunkwcodes why is that?

**Comment by jonathanslenders** [comment]
It looks good to me, actually. Prompt_toolkit is a good choice for any terminal UI.
(Although the documentation for full screen applications and the set of built-in widgets could be improved.)
