### ISSUE TITLE
When I use a validator for prompt_toolkit.PromptSession.prompt() and I scroll while typing, the input continues in another line.

### ISSUE THREAD

**Issue by txhx38** [prompt-toolkit/python-prompt-toolkit#936]
When I use a validator like so:
```
prompt_toolkit.PromptSession.prompt(
    validator = a_validator(),
    validate_while_typing=True
)
```
and a ValidationError() is raised there is an issue.
When I run this and I scroll down, the input continues on a lower line. Also when I scroll up again.

**Comment by idoob** [comment]
I had a similar issue.  I had two prompts where the first one contains a validator but the second prompt does not have a validator. However, after responding to the second prompt, the validator exception from the previous prompt was raised. 

```
    responses['path'] = session.prompt(
        "Enter the file path: ", 
         validator=ThreadedValidator(PathValidator()), 
         validate_while_typing=False
    )

    responses['host'] = session.prompt(
        "Enter the hostname or IP Address: "
    )
```

Validator Used: 
```
class PathValidator(Validator):
    def validate(self, document):
        text = document.text

        file = pathlib.Path(document.text)
        if file.exists() == False:
            raise ValidationError(message='This path does not resolve')
```
The workaround I found was to stop using the  `PromptSession` and just use `prompt` instead.
