### ISSUE TITLE
Run Processor before Completer

### ISSUE THREAD

**Issue by sum-catnip** [prompt-toolkit/python-prompt-toolkit#965]
Hey, is there any way I can get my custom input processor to always execute before the completer? My completer relies on an action that happens inside the processor so the processor needs to already have been executed for the current input.

Have a nice day 👌

**Comment by jonathanslenders** [comment]
Hi @sum-catnip,

This is not possible within prompt_toolkit due to the order in which things execute. Would it not be possible for you to run the call the same transformation of that input processor in the completer code?

**Comment by sum-catnip** [comment]
yeah, i was thinking about that but that would've been a pretty dirty solution for me and i was thinking there must be a better way ^^ I ended up using the buffers on_text_changed. Thanks for answering and thanks for your work on this awesome project :D

![shellter](https://cdn.discordapp.com/attachments/567379308914540545/620681921978171413/shellter.gif)
