### ISSUE TITLE
Something wrong in jupyter

### ISSUE THREAD

**Issue by kingice** [prompt-toolkit/python-prompt-toolkit#986]
When use the prompt in jupyter , there is an error . It couldn't redirect input  to the Jupyter Input?
After reading the doc, I can't find the solution. Thanks for help!
<img width="936" alt="WechatIMG874" src="https://user-images.githubusercontent.com/4256391/67157270-8d058200-f35c-11e9-8e89-053b7e3c59d3.png">

**Comment by jonathanslenders** [comment]
Hi @kingice,

prompt_toolkit does not work in a jupyter notebook. It only works in real terminal or terminal emulator. Something that supports vt100 escape sequences or the Windows console.

Looks like there is a grammar mistake in the warning we have to fix though. ("Input is not a terminal")

**Comment by kingice** [comment]
> Hi @kingice,
> 
> prompt_toolkit does not work in a jupyter notebook. It only works in real terminal or terminal emulator. Something that supports vt100 escape sequences or the Windows console.
> 
> Looks like there is a grammar mistake in the warning we have to fix though. ("Input is not a terminal")

Got it ! Thanks!!
