### ISSUE TITLE
Maybe some bug in FuzzyCompleter

### ISSUE THREAD

**Issue by kingice** [prompt-toolkit/python-prompt-toolkit#988]
I run the example fuzzy_custom_completer.py,Then  modifed it to verify an idea, but it didn't work.
The code is bellow:
#!/usr/bin/env python
"""
Demonstration of a custom completer wrapped in a `FuzzyCompleter` for fuzzy
matching.
"""
from prompt_toolkit.completion import Completer, Completion, FuzzyCompleter
from prompt_toolkit.output.color_depth import ColorDepth
from prompt_toolkit.shortcuts import CompleteStyle, prompt

colors = ['red', 'blue', 'green', 'orange', 'purple', 'yellow', 'cyan',
          'magenta', 'pink']

class ColorCompleter(Completer):
    def get_completions(self, document, complete_event):
        word = document.get_word_before_cursor()
        for color in colors:
            if color.startswith(word):
                yield Completion(
                    color,
                    display = color+"test",
                    display_meta = "w",
                    start_position=-len(word),
                    style='fg:' + color,
                    selected_style='fg:white bg:' + color)

def main():
    # Simple completion menu.
    print('(The completion menu displays colors.)')
    prompt('Type a color: ', completer=FuzzyCompleter(ColorCompleter()))

    # Multi-column menu.
    prompt('Type a color: ', completer=FuzzyCompleter(ColorCompleter()),
           complete_style=CompleteStyle.MULTI_COLUMN)

    # Readline-like
    prompt('Type a color: ', completer=FuzzyCompleter(ColorCompleter()),
           complete_style=CompleteStyle.READLINE_LIKE)

if __name__ == '__main__':
    main()

The parameter "display" in  Completion is not work.It didn't  show the "test" suffix. The screen shot like:
![1571849365805](https://user-images.githubusercontent.com/4256391/67415744-27352680-f5f8-11e9-9d16-66a9ce460719.jpg)

**Comment by nebbles** [comment]
Could you format the code in your question using ``` before and after. In the editor it should look like
```
```python
# your code here```
```

Also if you start with saying what you were intending to do...

**Comment by nebbles** [comment]
Having taken your code, a quick fix seems to be removing the wrapper to `FuzzyCompleter()`

this code works more as you intended:
```python
from prompt_toolkit.completion import Completer, Completion, FuzzyCompleter
from prompt_toolkit.output.color_depth import ColorDepth
from prompt_toolkit.shortcuts import CompleteStyle, prompt

colors = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "yellow",
    "cyan",
    "magenta",
    "pink",
]


class ColorCompleter(Completer):
    def get_completions(self, document, complete_event):
        word = document.get_word_before_cursor()

        for color in colors:
            if color.startswith(word):
                yield Completion(
                    color,
                    display=color + "test",
                    display_meta="w",
                    start_position=-len(word),
                    style="fg:" + color,
                    selected_style="fg:white bg:" + color,
                )


def main():
    # Simple completion menu.
    print("(The completion menu displays colors.)")
    prompt("Type a color: ", completer=FuzzyCompleter(ColorCompleter()))


# Multi-column menu.
prompt(
    "Type a color: ",
    # completer=FuzzyCompleter(ColorCompleter()),
    completer=ColorCompleter(),
    complete_style=CompleteStyle.MULTI_COLUMN,
)

# Readline-like
# prompt(
#     "Type a color: ",
#     completer=FuzzyCompleter(ColorCompleter()),
#     complete_style=CompleteStyle.READLINE_LIKE,
# )

if __name__ == "__main__":
    main()

```

<img width="191" alt="image" src="https://user-images.githubusercontent.com/12599555/68530227-77053480-02fe-11ea-9678-d6df1605eee1.png">

This is probably to do with how the FuzzyCompleter() wrapper handles outputting text to the autocomplete menu. My recommendation is you create a single class that implements both the modification you are trying to have, as well as the Fuzzy completion. That way you fully control the output from the completer.

**Comment by kingice** [comment]
> ```python
> from prompt_toolkit.completion import Completer, Completion, FuzzyCompleter
> from prompt_toolkit.output.color_depth import ColorDepth
> from prompt_toolkit.shortcuts import CompleteStyle, prompt
> 
> colors = [
>     "red",
>     "blue",
>     "green",
>     "orange",
>     "purple",
>     "yellow",
>     "cyan",
>     "magenta",
>     "pink",
> ]
> 
> 
> class ColorCompleter(Completer):
>     def get_completions(self, document, complete_event):
>         word = document.get_word_before_cursor()
> 
>         for color in colors:
>             if color.startswith(word):
>                 yield Completion(
>                     color,
>                     display=color + "test",
>                     display_meta="w",
>                     start_position=-len(word),
>                     style="fg:" + color,
>                     selected_style="fg:white bg:" + color,
>                 )
> 
> 
> def main():
>     # Simple completion menu.
>     print("(The completion menu displays colors.)")
>     prompt("Type a color: ", completer=FuzzyCompleter(ColorCompleter()))
> 
> 
> # Multi-column menu.
> prompt(
>     "Type a color: ",
>     # completer=FuzzyCompleter(ColorCompleter()),
>     completer=ColorCompleter(),
>     complete_style=CompleteStyle.MULTI_COLUMN,
> )
> 
> # Readline-like
> # prompt(
> #     "Type a color: ",
> #     completer=FuzzyCompleter(ColorCompleter()),
> #     complete_style=CompleteStyle.READLINE_LIKE,
> # )
> 
> if __name__ == "__main__":
>     main()
> ```

Thanks a lot for your reply!!
Your suggestion is very helpful! I will improve it next time!!Really Thanks!

**Comment by nebbles** [comment]
Glad to help - I suggest this issue is closed now.

**Comment by jonathanslenders** [comment]
Thanks @nebbles, for helping out!
